// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// This object defines account permissions for users who are associated with the account permission profile. 
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountRoleSettings : IAdditionalDataHolder, IParsable
    {
        /// <summary>The accountAgreementsAccessType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountAgreementsAccessType { get; set; }
#nullable restore
#else
        public string AccountAgreementsAccessType { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AccountAgreementsAccessTypeMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AccountAgreementsAccessTypeMetadata { get; set; }
#endif
        /// <summary>The accountManagementGranular property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.AccountManagementGranular? AccountManagementGranular { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.AccountManagementGranular AccountManagementGranular { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When **true,** users have full administrative access to the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowAccountManagement { get; set; }
#nullable restore
#else
        public string AllowAccountManagement { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowAccountManagementMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowAccountManagementMetadata { get; set; }
#endif
        /// <summary>When **true,** users can manage documents by using the API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowApiAccess { get; set; }
#nullable restore
#else
        public string AllowApiAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowApiAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowApiAccessMetadata { get; set; }
#endif
        /// <summary>When **true,** users can access the account by using the eSignature API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowApiAccessToAccount { get; set; }
#nullable restore
#else
        public string AllowApiAccessToAccount { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowApiAccessToAccountMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowApiAccessToAccountMetadata { get; set; }
#endif
        /// <summary>When **true,** users can send envelopes on behalf of others.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowApiSendingOnBehalfOfOthers { get; set; }
#nullable restore
#else
        public string AllowApiSendingOnBehalfOfOthers { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowApiSendingOnBehalfOfOthersMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowApiSendingOnBehalfOfOthersMetadata { get; set; }
#endif
        /// <summary>When **true,** users may specify sequential signing recipients when they send documents by using the API.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowApiSequentialSigning { get; set; }
#nullable restore
#else
        public string AllowApiSequentialSigning { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowApiSequentialSigningMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowApiSequentialSigningMetadata { get; set; }
#endif
        /// <summary> When **true,** auto-tagging is enabled for the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowAutoTagging { get; set; }
#nullable restore
#else
        public string AllowAutoTagging { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowAutoTaggingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowAutoTaggingMetadata { get; set; }
#endif
        /// <summary>When **true,** bulk sending is enabled for users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowBulkSending { get; set; }
#nullable restore
#else
        public string AllowBulkSending { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowBulkSendingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowBulkSendingMetadata { get; set; }
#endif
        /// <summary>When **true,** the Docusign Desktop Client is enabled for users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowDocuSignDesktopClient { get; set; }
#nullable restore
#else
        public string AllowDocuSignDesktopClient { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowDocuSignDesktopClientMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowDocuSignDesktopClientMetadata { get; set; }
#endif
        /// <summary>Specifies the level of access that users have to the account&apos;s address book. Valid values are:- `personal`- `useShared`- `usePersonalAndShared`- `personalAndShared`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedAddressBookAccess { get; set; }
#nullable restore
#else
        public string AllowedAddressBookAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedAddressBookAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedAddressBookAccessMetadata { get; set; }
#endif
        /// <summary>The allowedClickwrapsAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedClickwrapsAccess { get; set; }
#nullable restore
#else
        public string AllowedClickwrapsAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedClickwrapsAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedClickwrapsAccessMetadata { get; set; }
#endif
        /// <summary>The allowedDocumentTemplateLibraryAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedDocumentTemplateLibraryAccess { get; set; }
#nullable restore
#else
        public string AllowedDocumentTemplateLibraryAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedDocumentTemplateLibraryAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedDocumentTemplateLibraryAccessMetadata { get; set; }
#endif
        /// <summary>The allowedOrchestrationAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedOrchestrationAccess { get; set; }
#nullable restore
#else
        public string AllowedOrchestrationAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedOrchestrationAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedOrchestrationAccessMetadata { get; set; }
#endif
        /// <summary>Specifies the level of access that users have to account templates. Valid values are: - `none` - `use`- `create`- `share`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedTemplateAccess { get; set; }
#nullable restore
#else
        public string AllowedTemplateAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedTemplateAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedTemplateAccessMetadata { get; set; }
#endif
        /// <summary>When **true,** users can be recipients of envelopes transferred to them by administrators of other accounts. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowedToBeEnvelopeTransferRecipient { get; set; }
#nullable restore
#else
        public string AllowedToBeEnvelopeTransferRecipient { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowedToBeEnvelopeTransferRecipientMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowedToBeEnvelopeTransferRecipientMetadata { get; set; }
#endif
        /// <summary>When **true,** users can send envelopes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowEnvelopeSending { get; set; }
#nullable restore
#else
        public string AllowEnvelopeSending { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowEnvelopeSendingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowEnvelopeSendingMetadata { get; set; }
#endif
        /// <summary>When **true,** users can add electronic seal ([eSeal](https://support.docusign.com/s/document-item?bundleId=xcm1643837555908&amp;topicId=isl1578456577247.html)) recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowESealRecipients { get; set; }
#nullable restore
#else
        public string AllowESealRecipients { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowESealRecipientsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowESealRecipientsMetadata { get; set; }
#endif
        /// <summary>When **true,** PowerForm Administrators can access all of the PowerForm envelopes associated with the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowPowerFormsAdminToAccessAllPowerFormEnvelopes { get; set; }
#nullable restore
#else
        public string AllowPowerFormsAdminToAccessAllPowerFormEnvelopes { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata { get; set; }
#endif
        /// <summary>When **true,** senders can set the language of the email that is sent to recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowSendersToSetRecipientEmailLanguage { get; set; }
#nullable restore
#else
        public string AllowSendersToSetRecipientEmailLanguage { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowSendersToSetRecipientEmailLanguageMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowSendersToSetRecipientEmailLanguageMetadata { get; set; }
#endif
        /// <summary>When **true,** users can add requests for attachments from signers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowSignerAttachments { get; set; }
#nullable restore
#else
        public string AllowSignerAttachments { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowSignerAttachmentsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowSignerAttachmentsMetadata { get; set; }
#endif
        /// <summary>When **true,** senders can include supplemental documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowSupplementalDocuments { get; set; }
#nullable restore
#else
        public string AllowSupplementalDocuments { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowSupplementalDocumentsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowSupplementalDocumentsMetadata { get; set; }
#endif
        /// <summary>When **true,** the tagger palette is visible during the sending and correct flows and users can add tabs to documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowTaggingInSendAndCorrect { get; set; }
#nullable restore
#else
        public string AllowTaggingInSendAndCorrect { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowTaggingInSendAndCorrectMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowTaggingInSendAndCorrectMetadata { get; set; }
#endif
        /// <summary>The allowTransactions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowTransactions { get; set; }
#nullable restore
#else
        public string AllowTransactions { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowTransactionsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowTransactionsMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowVaulting { get; set; }
#nullable restore
#else
        public string AllowVaulting { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowVaultingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowVaultingMetadata { get; set; }
#endif
        /// <summary>When **true,** users can override the default account setting that controls whether recipients can sign documents on paper. The option to overrride this setting occurs during the sending process on a per-envelope basis.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllowWetSigningOverride { get; set; }
#nullable restore
#else
        public string AllowWetSigningOverride { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? AllowWetSigningOverrideMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata AllowWetSigningOverrideMetadata { get; set; }
#endif
        /// <summary>The canBulkUploadAgreements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanBulkUploadAgreements { get; set; }
#nullable restore
#else
        public string CanBulkUploadAgreements { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanBulkUploadAgreementsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanBulkUploadAgreementsMetadata { get; set; }
#endif
        /// <summary>The canCreateTransaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanCreateTransaction { get; set; }
#nullable restore
#else
        public string CanCreateTransaction { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanCreateTransactionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanCreateTransactionMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanCreateWorkspaces { get; set; }
#nullable restore
#else
        public string CanCreateWorkspaces { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanCreateWorkspacesMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanCreateWorkspacesMetadata { get; set; }
#endif
        /// <summary>The canDeleteDocumentsInTransaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanDeleteDocumentsInTransaction { get; set; }
#nullable restore
#else
        public string CanDeleteDocumentsInTransaction { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanDeleteDocumentsInTransactionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanDeleteDocumentsInTransactionMetadata { get; set; }
#endif
        /// <summary>The canDeleteTransaction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanDeleteTransaction { get; set; }
#nullable restore
#else
        public string CanDeleteTransaction { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanDeleteTransactionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanDeleteTransactionMetadata { get; set; }
#endif
        /// <summary>The canManageAgreementDeskRequest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanManageAgreementDeskRequest { get; set; }
#nullable restore
#else
        public string CanManageAgreementDeskRequest { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanManageAgreementDeskRequestMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanManageAgreementDeskRequestMetadata { get; set; }
#endif
        /// <summary>The canManageAgreementDeskRequestSetting property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanManageAgreementDeskRequestSetting { get; set; }
#nullable restore
#else
        public string CanManageAgreementDeskRequestSetting { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanManageAgreementDeskRequestSettingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanManageAgreementDeskRequestSettingMetadata { get; set; }
#endif
        /// <summary>The canSendEnvelopesViaSMS property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanSendEnvelopesViaSMS { get; set; }
#nullable restore
#else
        public string CanSendEnvelopesViaSMS { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? CanSendEnvelopesViaSMSMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata CanSendEnvelopesViaSMSMetadata { get; set; }
#endif
        /// <summary>When **true,** users cannot upload documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisableDocumentUpload { get; set; }
#nullable restore
#else
        public string DisableDocumentUpload { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? DisableDocumentUploadMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata DisableDocumentUploadMetadata { get; set; }
#endif
        /// <summary>When **true,** users can access the **Other Actions** menu.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisableOtherActions { get; set; }
#nullable restore
#else
        public string DisableOtherActions { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? DisableOtherActionsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata DisableOtherActionsMetadata { get; set; }
#endif
        /// <summary>When **true,** API request logging is enabled.**Note:** Logging limits apply.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableApiRequestLogging { get; set; }
#nullable restore
#else
        public string EnableApiRequestLogging { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? EnableApiRequestLoggingMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata EnableApiRequestLoggingMetadata { get; set; }
#endif
        /// <summary>The enableKeyTermsSuggestionsByDocumentType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableKeyTermsSuggestionsByDocumentType { get; set; }
#nullable restore
#else
        public string EnableKeyTermsSuggestionsByDocumentType { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? EnableKeyTermsSuggestionsByDocumentTypeMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata EnableKeyTermsSuggestionsByDocumentTypeMetadata { get; set; }
#endif
        /// <summary>When **true,** senders are notified when recipients view the documents that they send.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableRecipientViewingNotifications { get; set; }
#nullable restore
#else
        public string EnableRecipientViewingNotifications { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? EnableRecipientViewingNotificationsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata EnableRecipientViewingNotificationsMetadata { get; set; }
#endif
        /// <summary>When **true,** the sequential signing user interface is enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableSequentialSigningInterface { get; set; }
#nullable restore
#else
        public string EnableSequentialSigningInterface { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? EnableSequentialSigningInterfaceMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata EnableSequentialSigningInterfaceMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableTransactionPointIntegration { get; set; }
#nullable restore
#else
        public string EnableTransactionPointIntegration { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? EnableTransactionPointIntegrationMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata EnableTransactionPointIntegrationMetadata { get; set; }
#endif
        /// <summary>The playbookAccess property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaybookAccess { get; set; }
#nullable restore
#else
        public string PlaybookAccess { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? PlaybookAccessMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata PlaybookAccessMetadata { get; set; }
#endif
        /// <summary>The PowerForms rights associated with the account permission profile. Valid values are:- `none` - `user` - `admin`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerFormRole { get; set; }
#nullable restore
#else
        public string PowerFormRole { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? PowerFormRoleMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata PowerFormRoleMetadata { get; set; }
#endif
        /// <summary>When **true,** senders receive emails about completed, self-signed documents that contain links to the completed documents instead of PDF attachments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceiveCompletedSelfSignedDocumentsAsEmailLinks { get; set; }
#nullable restore
#else
        public string ReceiveCompletedSelfSignedDocumentsAsEmailLinks { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? SigningUiVersionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata SigningUiVersionMetadata { get; set; }
#endif
        /// <summary>When **true,** senders can require recipients to accept supplemental documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplementalDocumentsMustAccept { get; set; }
#nullable restore
#else
        public string SupplementalDocumentsMustAccept { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? SupplementalDocumentsMustAcceptMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata SupplementalDocumentsMustAcceptMetadata { get; set; }
#endif
        /// <summary>When **true,** senders can require recipients to read supplemental documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplementalDocumentsMustRead { get; set; }
#nullable restore
#else
        public string SupplementalDocumentsMustRead { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? SupplementalDocumentsMustReadMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata SupplementalDocumentsMustReadMetadata { get; set; }
#endif
        /// <summary>When **true,** users can require recipients to view supplemental documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupplementalDocumentsMustView { get; set; }
#nullable restore
#else
        public string SupplementalDocumentsMustView { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? SupplementalDocumentsMustViewMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata SupplementalDocumentsMustViewMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseNewDocuSignExperienceInterface { get; set; }
#nullable restore
#else
        public string UseNewDocuSignExperienceInterface { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? UseNewDocuSignExperienceInterfaceMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata UseNewDocuSignExperienceInterfaceMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UseNewSendingInterface { get; set; }
#nullable restore
#else
        public string UseNewSendingInterface { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? UseNewSendingInterfaceMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata UseNewSendingInterfaceMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VaultingMode { get; set; }
#nullable restore
#else
        public string VaultingMode { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? VaultingModeMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata VaultingModeMetadata { get; set; }
#endif
        /// <summary>The webForms property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebForms { get; set; }
#nullable restore
#else
        public string WebForms { get; set; }
#endif
        /// <summary>Metadata that indicates whether a property is editable and describes setting-specific options.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.SettingsMetadata? WebFormsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.SettingsMetadata WebFormsMetadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.AccountRoleSettings"/> and sets the default values.
        /// </summary>
        public AccountRoleSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.AccountRoleSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.AccountRoleSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.AccountRoleSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountAgreementsAccessType", n => { AccountAgreementsAccessType = n.GetStringValue(); } },
                { "accountAgreementsAccessTypeMetadata", n => { AccountAgreementsAccessTypeMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "accountManagementGranular", n => { AccountManagementGranular = n.GetObjectValue<global::DocuSignKiota.Client.Models.AccountManagementGranular>(global::DocuSignKiota.Client.Models.AccountManagementGranular.CreateFromDiscriminatorValue); } },
                { "allowAccountManagement", n => { AllowAccountManagement = n.GetStringValue(); } },
                { "allowAccountManagementMetadata", n => { AllowAccountManagementMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowApiAccess", n => { AllowApiAccess = n.GetStringValue(); } },
                { "allowApiAccessMetadata", n => { AllowApiAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowApiAccessToAccount", n => { AllowApiAccessToAccount = n.GetStringValue(); } },
                { "allowApiAccessToAccountMetadata", n => { AllowApiAccessToAccountMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowApiSendingOnBehalfOfOthers", n => { AllowApiSendingOnBehalfOfOthers = n.GetStringValue(); } },
                { "allowApiSendingOnBehalfOfOthersMetadata", n => { AllowApiSendingOnBehalfOfOthersMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowApiSequentialSigning", n => { AllowApiSequentialSigning = n.GetStringValue(); } },
                { "allowApiSequentialSigningMetadata", n => { AllowApiSequentialSigningMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowAutoTagging", n => { AllowAutoTagging = n.GetStringValue(); } },
                { "allowAutoTaggingMetadata", n => { AllowAutoTaggingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowBulkSending", n => { AllowBulkSending = n.GetStringValue(); } },
                { "allowBulkSendingMetadata", n => { AllowBulkSendingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowDocuSignDesktopClient", n => { AllowDocuSignDesktopClient = n.GetStringValue(); } },
                { "allowDocuSignDesktopClientMetadata", n => { AllowDocuSignDesktopClientMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowESealRecipients", n => { AllowESealRecipients = n.GetStringValue(); } },
                { "allowESealRecipientsMetadata", n => { AllowESealRecipientsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowEnvelopeSending", n => { AllowEnvelopeSending = n.GetStringValue(); } },
                { "allowEnvelopeSendingMetadata", n => { AllowEnvelopeSendingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowPowerFormsAdminToAccessAllPowerFormEnvelopes", n => { AllowPowerFormsAdminToAccessAllPowerFormEnvelopes = n.GetStringValue(); } },
                { "allowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata", n => { AllowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowSendersToSetRecipientEmailLanguage", n => { AllowSendersToSetRecipientEmailLanguage = n.GetStringValue(); } },
                { "allowSendersToSetRecipientEmailLanguageMetadata", n => { AllowSendersToSetRecipientEmailLanguageMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowSignerAttachments", n => { AllowSignerAttachments = n.GetStringValue(); } },
                { "allowSignerAttachmentsMetadata", n => { AllowSignerAttachmentsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowSupplementalDocuments", n => { AllowSupplementalDocuments = n.GetStringValue(); } },
                { "allowSupplementalDocumentsMetadata", n => { AllowSupplementalDocumentsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowTaggingInSendAndCorrect", n => { AllowTaggingInSendAndCorrect = n.GetStringValue(); } },
                { "allowTaggingInSendAndCorrectMetadata", n => { AllowTaggingInSendAndCorrectMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowTransactions", n => { AllowTransactions = n.GetStringValue(); } },
                { "allowTransactionsMetadata", n => { AllowTransactionsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowVaulting", n => { AllowVaulting = n.GetStringValue(); } },
                { "allowVaultingMetadata", n => { AllowVaultingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowWetSigningOverride", n => { AllowWetSigningOverride = n.GetStringValue(); } },
                { "allowWetSigningOverrideMetadata", n => { AllowWetSigningOverrideMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedAddressBookAccess", n => { AllowedAddressBookAccess = n.GetStringValue(); } },
                { "allowedAddressBookAccessMetadata", n => { AllowedAddressBookAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedClickwrapsAccess", n => { AllowedClickwrapsAccess = n.GetStringValue(); } },
                { "allowedClickwrapsAccessMetadata", n => { AllowedClickwrapsAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedDocumentTemplateLibraryAccess", n => { AllowedDocumentTemplateLibraryAccess = n.GetStringValue(); } },
                { "allowedDocumentTemplateLibraryAccessMetadata", n => { AllowedDocumentTemplateLibraryAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedOrchestrationAccess", n => { AllowedOrchestrationAccess = n.GetStringValue(); } },
                { "allowedOrchestrationAccessMetadata", n => { AllowedOrchestrationAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedTemplateAccess", n => { AllowedTemplateAccess = n.GetStringValue(); } },
                { "allowedTemplateAccessMetadata", n => { AllowedTemplateAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "allowedToBeEnvelopeTransferRecipient", n => { AllowedToBeEnvelopeTransferRecipient = n.GetStringValue(); } },
                { "allowedToBeEnvelopeTransferRecipientMetadata", n => { AllowedToBeEnvelopeTransferRecipientMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canBulkUploadAgreements", n => { CanBulkUploadAgreements = n.GetStringValue(); } },
                { "canBulkUploadAgreementsMetadata", n => { CanBulkUploadAgreementsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canCreateTransaction", n => { CanCreateTransaction = n.GetStringValue(); } },
                { "canCreateTransactionMetadata", n => { CanCreateTransactionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canCreateWorkspaces", n => { CanCreateWorkspaces = n.GetStringValue(); } },
                { "canCreateWorkspacesMetadata", n => { CanCreateWorkspacesMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canDeleteDocumentsInTransaction", n => { CanDeleteDocumentsInTransaction = n.GetStringValue(); } },
                { "canDeleteDocumentsInTransactionMetadata", n => { CanDeleteDocumentsInTransactionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canDeleteTransaction", n => { CanDeleteTransaction = n.GetStringValue(); } },
                { "canDeleteTransactionMetadata", n => { CanDeleteTransactionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canManageAgreementDeskRequest", n => { CanManageAgreementDeskRequest = n.GetStringValue(); } },
                { "canManageAgreementDeskRequestMetadata", n => { CanManageAgreementDeskRequestMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canManageAgreementDeskRequestSetting", n => { CanManageAgreementDeskRequestSetting = n.GetStringValue(); } },
                { "canManageAgreementDeskRequestSettingMetadata", n => { CanManageAgreementDeskRequestSettingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "canSendEnvelopesViaSMS", n => { CanSendEnvelopesViaSMS = n.GetStringValue(); } },
                { "canSendEnvelopesViaSMSMetadata", n => { CanSendEnvelopesViaSMSMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "disableDocumentUpload", n => { DisableDocumentUpload = n.GetStringValue(); } },
                { "disableDocumentUploadMetadata", n => { DisableDocumentUploadMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "disableOtherActions", n => { DisableOtherActions = n.GetStringValue(); } },
                { "disableOtherActionsMetadata", n => { DisableOtherActionsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "enableApiRequestLogging", n => { EnableApiRequestLogging = n.GetStringValue(); } },
                { "enableApiRequestLoggingMetadata", n => { EnableApiRequestLoggingMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "enableKeyTermsSuggestionsByDocumentType", n => { EnableKeyTermsSuggestionsByDocumentType = n.GetStringValue(); } },
                { "enableKeyTermsSuggestionsByDocumentTypeMetadata", n => { EnableKeyTermsSuggestionsByDocumentTypeMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "enableRecipientViewingNotifications", n => { EnableRecipientViewingNotifications = n.GetStringValue(); } },
                { "enableRecipientViewingNotificationsMetadata", n => { EnableRecipientViewingNotificationsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "enableSequentialSigningInterface", n => { EnableSequentialSigningInterface = n.GetStringValue(); } },
                { "enableSequentialSigningInterfaceMetadata", n => { EnableSequentialSigningInterfaceMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "enableTransactionPointIntegration", n => { EnableTransactionPointIntegration = n.GetStringValue(); } },
                { "enableTransactionPointIntegrationMetadata", n => { EnableTransactionPointIntegrationMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "playbookAccess", n => { PlaybookAccess = n.GetStringValue(); } },
                { "playbookAccessMetadata", n => { PlaybookAccessMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "powerFormRole", n => { PowerFormRole = n.GetStringValue(); } },
                { "powerFormRoleMetadata", n => { PowerFormRoleMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "receiveCompletedSelfSignedDocumentsAsEmailLinks", n => { ReceiveCompletedSelfSignedDocumentsAsEmailLinks = n.GetStringValue(); } },
                { "receiveCompletedSelfSignedDocumentsAsEmailLinksMetadata", n => { ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "signingUiVersionMetadata", n => { SigningUiVersionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "supplementalDocumentsMustAccept", n => { SupplementalDocumentsMustAccept = n.GetStringValue(); } },
                { "supplementalDocumentsMustAcceptMetadata", n => { SupplementalDocumentsMustAcceptMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "supplementalDocumentsMustRead", n => { SupplementalDocumentsMustRead = n.GetStringValue(); } },
                { "supplementalDocumentsMustReadMetadata", n => { SupplementalDocumentsMustReadMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "supplementalDocumentsMustView", n => { SupplementalDocumentsMustView = n.GetStringValue(); } },
                { "supplementalDocumentsMustViewMetadata", n => { SupplementalDocumentsMustViewMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "useNewDocuSignExperienceInterface", n => { UseNewDocuSignExperienceInterface = n.GetStringValue(); } },
                { "useNewDocuSignExperienceInterfaceMetadata", n => { UseNewDocuSignExperienceInterfaceMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "useNewSendingInterface", n => { UseNewSendingInterface = n.GetStringValue(); } },
                { "useNewSendingInterfaceMetadata", n => { UseNewSendingInterfaceMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "vaultingMode", n => { VaultingMode = n.GetStringValue(); } },
                { "vaultingModeMetadata", n => { VaultingModeMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
                { "webForms", n => { WebForms = n.GetStringValue(); } },
                { "webFormsMetadata", n => { WebFormsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>(global::DocuSignKiota.Client.Models.SettingsMetadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountAgreementsAccessType", AccountAgreementsAccessType);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("accountAgreementsAccessTypeMetadata", AccountAgreementsAccessTypeMetadata);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.AccountManagementGranular>("accountManagementGranular", AccountManagementGranular);
            writer.WriteStringValue("allowAccountManagement", AllowAccountManagement);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowAccountManagementMetadata", AllowAccountManagementMetadata);
            writer.WriteStringValue("allowApiAccess", AllowApiAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowApiAccessMetadata", AllowApiAccessMetadata);
            writer.WriteStringValue("allowApiAccessToAccount", AllowApiAccessToAccount);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowApiAccessToAccountMetadata", AllowApiAccessToAccountMetadata);
            writer.WriteStringValue("allowApiSendingOnBehalfOfOthers", AllowApiSendingOnBehalfOfOthers);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowApiSendingOnBehalfOfOthersMetadata", AllowApiSendingOnBehalfOfOthersMetadata);
            writer.WriteStringValue("allowApiSequentialSigning", AllowApiSequentialSigning);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowApiSequentialSigningMetadata", AllowApiSequentialSigningMetadata);
            writer.WriteStringValue("allowAutoTagging", AllowAutoTagging);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowAutoTaggingMetadata", AllowAutoTaggingMetadata);
            writer.WriteStringValue("allowBulkSending", AllowBulkSending);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowBulkSendingMetadata", AllowBulkSendingMetadata);
            writer.WriteStringValue("allowDocuSignDesktopClient", AllowDocuSignDesktopClient);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowDocuSignDesktopClientMetadata", AllowDocuSignDesktopClientMetadata);
            writer.WriteStringValue("allowedAddressBookAccess", AllowedAddressBookAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedAddressBookAccessMetadata", AllowedAddressBookAccessMetadata);
            writer.WriteStringValue("allowedClickwrapsAccess", AllowedClickwrapsAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedClickwrapsAccessMetadata", AllowedClickwrapsAccessMetadata);
            writer.WriteStringValue("allowedDocumentTemplateLibraryAccess", AllowedDocumentTemplateLibraryAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedDocumentTemplateLibraryAccessMetadata", AllowedDocumentTemplateLibraryAccessMetadata);
            writer.WriteStringValue("allowedOrchestrationAccess", AllowedOrchestrationAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedOrchestrationAccessMetadata", AllowedOrchestrationAccessMetadata);
            writer.WriteStringValue("allowedTemplateAccess", AllowedTemplateAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedTemplateAccessMetadata", AllowedTemplateAccessMetadata);
            writer.WriteStringValue("allowedToBeEnvelopeTransferRecipient", AllowedToBeEnvelopeTransferRecipient);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowedToBeEnvelopeTransferRecipientMetadata", AllowedToBeEnvelopeTransferRecipientMetadata);
            writer.WriteStringValue("allowEnvelopeSending", AllowEnvelopeSending);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowEnvelopeSendingMetadata", AllowEnvelopeSendingMetadata);
            writer.WriteStringValue("allowESealRecipients", AllowESealRecipients);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowESealRecipientsMetadata", AllowESealRecipientsMetadata);
            writer.WriteStringValue("allowPowerFormsAdminToAccessAllPowerFormEnvelopes", AllowPowerFormsAdminToAccessAllPowerFormEnvelopes);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata", AllowPowerFormsAdminToAccessAllPowerFormEnvelopesMetadata);
            writer.WriteStringValue("allowSendersToSetRecipientEmailLanguage", AllowSendersToSetRecipientEmailLanguage);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowSendersToSetRecipientEmailLanguageMetadata", AllowSendersToSetRecipientEmailLanguageMetadata);
            writer.WriteStringValue("allowSignerAttachments", AllowSignerAttachments);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowSignerAttachmentsMetadata", AllowSignerAttachmentsMetadata);
            writer.WriteStringValue("allowSupplementalDocuments", AllowSupplementalDocuments);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowSupplementalDocumentsMetadata", AllowSupplementalDocumentsMetadata);
            writer.WriteStringValue("allowTaggingInSendAndCorrect", AllowTaggingInSendAndCorrect);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowTaggingInSendAndCorrectMetadata", AllowTaggingInSendAndCorrectMetadata);
            writer.WriteStringValue("allowTransactions", AllowTransactions);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowTransactionsMetadata", AllowTransactionsMetadata);
            writer.WriteStringValue("allowVaulting", AllowVaulting);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowVaultingMetadata", AllowVaultingMetadata);
            writer.WriteStringValue("allowWetSigningOverride", AllowWetSigningOverride);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("allowWetSigningOverrideMetadata", AllowWetSigningOverrideMetadata);
            writer.WriteStringValue("canBulkUploadAgreements", CanBulkUploadAgreements);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canBulkUploadAgreementsMetadata", CanBulkUploadAgreementsMetadata);
            writer.WriteStringValue("canCreateTransaction", CanCreateTransaction);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canCreateTransactionMetadata", CanCreateTransactionMetadata);
            writer.WriteStringValue("canCreateWorkspaces", CanCreateWorkspaces);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canCreateWorkspacesMetadata", CanCreateWorkspacesMetadata);
            writer.WriteStringValue("canDeleteDocumentsInTransaction", CanDeleteDocumentsInTransaction);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canDeleteDocumentsInTransactionMetadata", CanDeleteDocumentsInTransactionMetadata);
            writer.WriteStringValue("canDeleteTransaction", CanDeleteTransaction);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canDeleteTransactionMetadata", CanDeleteTransactionMetadata);
            writer.WriteStringValue("canManageAgreementDeskRequest", CanManageAgreementDeskRequest);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canManageAgreementDeskRequestMetadata", CanManageAgreementDeskRequestMetadata);
            writer.WriteStringValue("canManageAgreementDeskRequestSetting", CanManageAgreementDeskRequestSetting);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canManageAgreementDeskRequestSettingMetadata", CanManageAgreementDeskRequestSettingMetadata);
            writer.WriteStringValue("canSendEnvelopesViaSMS", CanSendEnvelopesViaSMS);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("canSendEnvelopesViaSMSMetadata", CanSendEnvelopesViaSMSMetadata);
            writer.WriteStringValue("disableDocumentUpload", DisableDocumentUpload);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("disableDocumentUploadMetadata", DisableDocumentUploadMetadata);
            writer.WriteStringValue("disableOtherActions", DisableOtherActions);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("disableOtherActionsMetadata", DisableOtherActionsMetadata);
            writer.WriteStringValue("enableApiRequestLogging", EnableApiRequestLogging);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("enableApiRequestLoggingMetadata", EnableApiRequestLoggingMetadata);
            writer.WriteStringValue("enableKeyTermsSuggestionsByDocumentType", EnableKeyTermsSuggestionsByDocumentType);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("enableKeyTermsSuggestionsByDocumentTypeMetadata", EnableKeyTermsSuggestionsByDocumentTypeMetadata);
            writer.WriteStringValue("enableRecipientViewingNotifications", EnableRecipientViewingNotifications);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("enableRecipientViewingNotificationsMetadata", EnableRecipientViewingNotificationsMetadata);
            writer.WriteStringValue("enableSequentialSigningInterface", EnableSequentialSigningInterface);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("enableSequentialSigningInterfaceMetadata", EnableSequentialSigningInterfaceMetadata);
            writer.WriteStringValue("enableTransactionPointIntegration", EnableTransactionPointIntegration);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("enableTransactionPointIntegrationMetadata", EnableTransactionPointIntegrationMetadata);
            writer.WriteStringValue("playbookAccess", PlaybookAccess);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("playbookAccessMetadata", PlaybookAccessMetadata);
            writer.WriteStringValue("powerFormRole", PowerFormRole);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("powerFormRoleMetadata", PowerFormRoleMetadata);
            writer.WriteStringValue("receiveCompletedSelfSignedDocumentsAsEmailLinks", ReceiveCompletedSelfSignedDocumentsAsEmailLinks);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("receiveCompletedSelfSignedDocumentsAsEmailLinksMetadata", ReceiveCompletedSelfSignedDocumentsAsEmailLinksMetadata);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("signingUiVersionMetadata", SigningUiVersionMetadata);
            writer.WriteStringValue("supplementalDocumentsMustAccept", SupplementalDocumentsMustAccept);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("supplementalDocumentsMustAcceptMetadata", SupplementalDocumentsMustAcceptMetadata);
            writer.WriteStringValue("supplementalDocumentsMustRead", SupplementalDocumentsMustRead);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("supplementalDocumentsMustReadMetadata", SupplementalDocumentsMustReadMetadata);
            writer.WriteStringValue("supplementalDocumentsMustView", SupplementalDocumentsMustView);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("supplementalDocumentsMustViewMetadata", SupplementalDocumentsMustViewMetadata);
            writer.WriteStringValue("useNewDocuSignExperienceInterface", UseNewDocuSignExperienceInterface);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("useNewDocuSignExperienceInterfaceMetadata", UseNewDocuSignExperienceInterfaceMetadata);
            writer.WriteStringValue("useNewSendingInterface", UseNewSendingInterface);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("useNewSendingInterfaceMetadata", UseNewSendingInterfaceMetadata);
            writer.WriteStringValue("vaultingMode", VaultingMode);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("vaultingModeMetadata", VaultingModeMetadata);
            writer.WriteStringValue("webForms", WebForms);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.SettingsMetadata>("webFormsMetadata", WebFormsMetadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
