// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Contains information about a billing plan.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BillingPlan : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.AppStoreProduct>? AppStoreProducts { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.AppStoreProduct> AppStoreProducts { get; set; }
#endif
        /// <summary>Contains the `currencyCode` and `currencySymbol` for the alternate currency values for `envelopeFee`, `fixedFee`, and `seatFee` that are configured for this plan feature set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CurrencyPlanPrice>? CurrencyPlanPrices { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CurrencyPlanPrice> CurrencyPlanPrices { get; set; }
#endif
        /// <summary>When **true,** customer support is provided as part of the account plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EnableSupport { get; set; }
#nullable restore
#else
        public string EnableSupport { get; set; }
#endif
        /// <summary>The number of seats (users) included in the plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IncludedSeats { get; set; }
#nullable restore
#else
        public string IncludedSeats { get; set; }
#endif
        /// <summary>Any other percentage discount for the plan.Example: `&quot;0.00&quot;`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OtherDiscountPercent { get; set; }
#nullable restore
#else
        public string OtherDiscountPercent { get; set; }
#endif
        /// <summary> The payment cycle associated with the plan. Valid values: Monthly or Annually. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentCycle { get; set; }
#nullable restore
#else
        public string PaymentCycle { get; set; }
#endif
        /// <summary>The payment method used for the billing plan. Valid values are:- `NotSupported`- `CreditCard`- `PurchaseOrder`- `Premium`- `Freemium`- `FreeTrial`- `AppStore`- `DigitalExternal`- `DirectDebit`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethod { get; set; }
#nullable restore
#else
        public string PaymentMethod { get; set; }
#endif
        /// <summary>The per seat price for the plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PerSeatPrice { get; set; }
#nullable restore
#else
        public string PerSeatPrice { get; set; }
#endif
        /// <summary>Identifies the type of plan. Examples include:- `business`- `corporate`- `enterprise` - `free`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanClassification { get; set; }
#nullable restore
#else
        public string PlanClassification { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.FeatureSet>? PlanFeatureSets { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.FeatureSet> PlanFeatureSets { get; set; }
#endif
        /// <summary>Docusign&apos;s ID for the account plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanId { get; set; }
#nullable restore
#else
        public string PlanId { get; set; }
#endif
        /// <summary>The name of the billing plan.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlanName { get; set; }
#nullable restore
#else
        public string PlanName { get; set; }
#endif
        /// <summary>A complex type that returns information about any seat discounts. It contains the information `BeginSeatCount`, `EndSeatCount` and `SeatDiscountPercent`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.SeatDiscount>? SeatDiscounts { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.SeatDiscount> SeatDiscounts { get; set; }
#endif
        /// <summary>The support incident fee charged for each support incident.Example: `&quot;$0.00&quot;`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupportIncidentFee { get; set; }
#nullable restore
#else
        public string SupportIncidentFee { get; set; }
#endif
        /// <summary>The support plan fee charged for this plan.Example: `&quot;$0.00&quot;`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SupportPlanFee { get; set; }
#nullable restore
#else
        public string SupportPlanFee { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.BillingPlan"/> and sets the default values.
        /// </summary>
        public BillingPlan()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.BillingPlan"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.BillingPlan CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.BillingPlan();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appStoreProducts", n => { AppStoreProducts = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.AppStoreProduct>(global::DocuSignKiota.Client.Models.AppStoreProduct.CreateFromDiscriminatorValue)?.AsList(); } },
                { "currencyPlanPrices", n => { CurrencyPlanPrices = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CurrencyPlanPrice>(global::DocuSignKiota.Client.Models.CurrencyPlanPrice.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enableSupport", n => { EnableSupport = n.GetStringValue(); } },
                { "includedSeats", n => { IncludedSeats = n.GetStringValue(); } },
                { "otherDiscountPercent", n => { OtherDiscountPercent = n.GetStringValue(); } },
                { "paymentCycle", n => { PaymentCycle = n.GetStringValue(); } },
                { "paymentMethod", n => { PaymentMethod = n.GetStringValue(); } },
                { "perSeatPrice", n => { PerSeatPrice = n.GetStringValue(); } },
                { "planClassification", n => { PlanClassification = n.GetStringValue(); } },
                { "planFeatureSets", n => { PlanFeatureSets = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FeatureSet>(global::DocuSignKiota.Client.Models.FeatureSet.CreateFromDiscriminatorValue)?.AsList(); } },
                { "planId", n => { PlanId = n.GetStringValue(); } },
                { "planName", n => { PlanName = n.GetStringValue(); } },
                { "seatDiscounts", n => { SeatDiscounts = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SeatDiscount>(global::DocuSignKiota.Client.Models.SeatDiscount.CreateFromDiscriminatorValue)?.AsList(); } },
                { "supportIncidentFee", n => { SupportIncidentFee = n.GetStringValue(); } },
                { "supportPlanFee", n => { SupportPlanFee = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.AppStoreProduct>("appStoreProducts", AppStoreProducts);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CurrencyPlanPrice>("currencyPlanPrices", CurrencyPlanPrices);
            writer.WriteStringValue("enableSupport", EnableSupport);
            writer.WriteStringValue("includedSeats", IncludedSeats);
            writer.WriteStringValue("otherDiscountPercent", OtherDiscountPercent);
            writer.WriteStringValue("paymentCycle", PaymentCycle);
            writer.WriteStringValue("paymentMethod", PaymentMethod);
            writer.WriteStringValue("perSeatPrice", PerSeatPrice);
            writer.WriteStringValue("planClassification", PlanClassification);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FeatureSet>("planFeatureSets", PlanFeatureSets);
            writer.WriteStringValue("planId", PlanId);
            writer.WriteStringValue("planName", PlanName);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SeatDiscount>("seatDiscounts", SeatDiscounts);
            writer.WriteStringValue("supportIncidentFee", SupportIncidentFee);
            writer.WriteStringValue("supportPlanFee", SupportPlanFee);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
