// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// A list of bulk send batch summaries. 
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkSendBatchSummaries : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum number of envelopes the account is permitted to submit in a given batch.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BatchSizeLimit { get; set; }
#nullable restore
#else
        public string BatchSizeLimit { get; set; }
#endif
        /// <summary>An array of batch summaries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.BulkSendBatchSummary>? BulkBatchSummaries { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.BulkSendBatchSummary> BulkBatchSummaries { get; set; }
#endif
        /// <summary>The bulkProcessQueueLimit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BulkProcessQueueLimit { get; set; }
#nullable restore
#else
        public string BulkProcessQueueLimit { get; set; }
#endif
        /// <summary>The bulkProcessTotalQueued property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BulkProcessTotalQueued { get; set; }
#nullable restore
#else
        public string BulkProcessTotalQueued { get; set; }
#endif
        /// <summary>The last index position in the result set. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndPosition { get; set; }
#nullable restore
#else
        public string EndPosition { get; set; }
#endif
        /// <summary>The URI for the next chunk of records based on the search request. It is `null` if this is the last set of results for the search. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NextUri { get; set; }
#nullable restore
#else
        public string NextUri { get; set; }
#endif
        /// <summary>The URI for the prior chunk of records based on the search request. It is `null` if this is the first set of results for the search. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousUri { get; set; }
#nullable restore
#else
        public string PreviousUri { get; set; }
#endif
        /// <summary>Maximum number of envelopes an account is permitted to have in the queue at any one time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QueueLimit { get; set; }
#nullable restore
#else
        public string QueueLimit { get; set; }
#endif
        /// <summary>The number of results in this response. Because you can filter which entries are included in the response, this value is always less than or equal to the `totalSetSize`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultSetSize { get; set; }
#nullable restore
#else
        public string ResultSetSize { get; set; }
#endif
        /// <summary>The starting index position of the current result set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartPosition { get; set; }
#nullable restore
#else
        public string StartPosition { get; set; }
#endif
        /// <summary>The number of envelopes currently pending processing for the entire account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalQueued { get; set; }
#nullable restore
#else
        public string TotalQueued { get; set; }
#endif
        /// <summary>The total number of items in the result set. This value is always greater than or equal to the value of `resultSetSize`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalSetSize { get; set; }
#nullable restore
#else
        public string TotalSetSize { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.BulkSendBatchSummaries"/> and sets the default values.
        /// </summary>
        public BulkSendBatchSummaries()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.BulkSendBatchSummaries"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.BulkSendBatchSummaries CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.BulkSendBatchSummaries();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batchSizeLimit", n => { BatchSizeLimit = n.GetStringValue(); } },
                { "bulkBatchSummaries", n => { BulkBatchSummaries = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.BulkSendBatchSummary>(global::DocuSignKiota.Client.Models.BulkSendBatchSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bulkProcessQueueLimit", n => { BulkProcessQueueLimit = n.GetStringValue(); } },
                { "bulkProcessTotalQueued", n => { BulkProcessTotalQueued = n.GetStringValue(); } },
                { "endPosition", n => { EndPosition = n.GetStringValue(); } },
                { "nextUri", n => { NextUri = n.GetStringValue(); } },
                { "previousUri", n => { PreviousUri = n.GetStringValue(); } },
                { "queueLimit", n => { QueueLimit = n.GetStringValue(); } },
                { "resultSetSize", n => { ResultSetSize = n.GetStringValue(); } },
                { "startPosition", n => { StartPosition = n.GetStringValue(); } },
                { "totalQueued", n => { TotalQueued = n.GetStringValue(); } },
                { "totalSetSize", n => { TotalSetSize = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("batchSizeLimit", BatchSizeLimit);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.BulkSendBatchSummary>("bulkBatchSummaries", BulkBatchSummaries);
            writer.WriteStringValue("bulkProcessQueueLimit", BulkProcessQueueLimit);
            writer.WriteStringValue("bulkProcessTotalQueued", BulkProcessTotalQueued);
            writer.WriteStringValue("endPosition", EndPosition);
            writer.WriteStringValue("nextUri", NextUri);
            writer.WriteStringValue("previousUri", PreviousUri);
            writer.WriteStringValue("queueLimit", QueueLimit);
            writer.WriteStringValue("resultSetSize", ResultSetSize);
            writer.WriteStringValue("startPosition", StartPosition);
            writer.WriteStringValue("totalQueued", TotalQueued);
            writer.WriteStringValue("totalSetSize", TotalSetSize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
