// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// A rule that defines a set of recipients and the conditions under which they will be used for the envelope.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConditionalRecipientRule : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An array of conditions that define when the recipients will be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.ConditionalRecipientRuleCondition>? Conditions { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.ConditionalRecipientRuleCondition> Conditions { get; set; }
#endif
        /// <summary>An integer that specifies the order in which rules are processed.Lower values are processed before higher values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Order { get; set; }
#nullable restore
#else
        public string Order { get; set; }
#endif
        /// <summary>Describes a group of recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.RecipientGroup? RecipientGroup { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.RecipientGroup RecipientGroup { get; set; }
#endif
        /// <summary>The ID of the recipient to whom the condition will be applied. This value should match the `recipientId` defined in the recipient object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipientId { get; set; }
#nullable restore
#else
        public string RecipientId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.ConditionalRecipientRule"/> and sets the default values.
        /// </summary>
        public ConditionalRecipientRule()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.ConditionalRecipientRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.ConditionalRecipientRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.ConditionalRecipientRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "conditions", n => { Conditions = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.ConditionalRecipientRuleCondition>(global::DocuSignKiota.Client.Models.ConditionalRecipientRuleCondition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "order", n => { Order = n.GetStringValue(); } },
                { "recipientGroup", n => { RecipientGroup = n.GetObjectValue<global::DocuSignKiota.Client.Models.RecipientGroup>(global::DocuSignKiota.Client.Models.RecipientGroup.CreateFromDiscriminatorValue); } },
                { "recipientId", n => { RecipientId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.ConditionalRecipientRuleCondition>("conditions", Conditions);
            writer.WriteStringValue("order", Order);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.RecipientGroup>("recipientGroup", RecipientGroup);
            writer.WriteStringValue("recipientId", RecipientId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
