// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// This object provides details about a custom field.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomField : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type of custom field. Valid values are:- `text` (default)- `list`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomFieldType { get; set; }
#nullable restore
#else
        public string CustomFieldType { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>The ID of the custom field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldId { get; set; }
#nullable restore
#else
        public string FieldId { get; set; }
#endif
        /// <summary>For a list custom field, this is an array of strings that represent the items in a list. Maximum Length: 2,000 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ListItems { get; set; }
#nullable restore
#else
        public List<string> ListItems { get; set; }
#endif
        /// <summary>The name of the custom field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When **true,** the signer must complete the custom field.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Required { get; set; }
#nullable restore
#else
        public string Required { get; set; }
#endif
        /// <summary>When **true,** the custom field displays at the top of the Certificate of Completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Show { get; set; }
#nullable restore
#else
        public string Show { get; set; }
#endif
        /// <summary>Specifies the value of the custom field. Maximum Length: 2,000 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.CustomField"/> and sets the default values.
        /// </summary>
        public CustomField()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.CustomField"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.CustomField CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.CustomField();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customFieldType", n => { CustomFieldType = n.GetStringValue(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "fieldId", n => { FieldId = n.GetStringValue(); } },
                { "listItems", n => { ListItems = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "required", n => { Required = n.GetStringValue(); } },
                { "show", n => { Show = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("customFieldType", CustomFieldType);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("fieldId", FieldId);
            writer.WriteCollectionOfPrimitiveValues<string>("listItems", ListItems);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("required", Required);
            writer.WriteStringValue("show", Show);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
