// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// This object contains information used toconfigure [eNote][eNote] functionality.To use eNote, the Allow eNote for eOriginal account plan item must be on,and the Connect configuration for eOriginal must be set correctly.[eNote]: https://support.docusign.com/s/document-item?bundleId=pik1583277475390&amp;topicId=tsn1583277394951.html
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ENoteConfiguration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The apiKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiKey { get; set; }
#nullable restore
#else
        public string ApiKey { get; set; }
#endif
        /// <summary>When **false,** the user must configure Connect and eOriginal for the integration to work.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectConfigured { get; set; }
#nullable restore
#else
        public string ConnectConfigured { get; set; }
#endif
        /// <summary>When **false,** the user must configure eNote for the feature to work.**Note:** In the account settings, `allowENoteEOriginal` must be **true**to make changes to the configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ENoteConfigured { get; set; }
#nullable restore
#else
        public string ENoteConfigured { get; set; }
#endif
        /// <summary>The name of the organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Organization { get; set; }
#nullable restore
#else
        public string Organization { get; set; }
#endif
        /// <summary>The user&apos;s password.This property is used only when adding a new user via a [Users: create](/docs/esign-rest-api/reference/users/users/create/) request. The value must conform to the password rules defined in the account [Security Settings](https://apps-d.docusign.com/admin/authenticate?goTo=securityInfo).This property is not returned by `GET` requests and cannot be updated via `PUT` requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Password { get; set; }
#nullable restore
#else
        public string Password { get; set; }
#endif
        /// <summary>The user&apos;s username.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.ENoteConfiguration"/> and sets the default values.
        /// </summary>
        public ENoteConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.ENoteConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.ENoteConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.ENoteConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiKey", n => { ApiKey = n.GetStringValue(); } },
                { "connectConfigured", n => { ConnectConfigured = n.GetStringValue(); } },
                { "eNoteConfigured", n => { ENoteConfigured = n.GetStringValue(); } },
                { "organization", n => { Organization = n.GetStringValue(); } },
                { "password", n => { Password = n.GetStringValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiKey", ApiKey);
            writer.WriteStringValue("connectConfigured", ConnectConfigured);
            writer.WriteStringValue("eNoteConfigured", ENoteConfigured);
            writer.WriteStringValue("organization", Organization);
            writer.WriteStringValue("password", Password);
            writer.WriteStringValue("userName", UserName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
