// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Lists of envelope and transaction IDs to use in the results.If you use this request body with Envelopes: listStatus,you must set one or both of the following query parametersto the special value `request_body`:- `envelope_ids=request_body`- `transaction_ids=request_body`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvelopeIdsRequest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A comma-separated list of envelope IDs to include in the results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EnvelopeIds { get; set; }
#nullable restore
#else
        public List<string> EnvelopeIds { get; set; }
#endif
        /// <summary>A comma-separated list of transaction IDs to include in the results. Note that transaction IDs are valid for seven days.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? TransactionIds { get; set; }
#nullable restore
#else
        public List<string> TransactionIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.EnvelopeIdsRequest"/> and sets the default values.
        /// </summary>
        public EnvelopeIdsRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.EnvelopeIdsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.EnvelopeIdsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.EnvelopeIdsRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "envelopeIds", n => { EnvelopeIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "transactionIds", n => { TransactionIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("envelopeIds", EnvelopeIds);
            writer.WriteCollectionOfPrimitiveValues<string>("transactionIds", TransactionIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
