// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Document tabs are tabs that are associated with a document rather than with a recipient.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EnvelopeDocumentTabs : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of[Approve tabs][approve].An Approve tab enablesthe recipient to approve documents withoutplacing a signature or initials on the document. If therecipient clicks the tab during the signing process, therecipient is considered to have signed the document. Noinformation is shown on the document of the approval, but itis recorded as a signature in the envelope history.The value of an approve tab can&apos;t be set.[approve]:          /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Approve>? ApproveTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Approve> ApproveTabs { get; set; }
#endif
        /// <summary>A list of[Checkbox tabs][checkbox].A Checkbox tab enables the recipient to select a yes/no (on/off) option. This value can be set.[checkbox]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Checkbox>? CheckboxTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Checkbox> CheckboxTabs { get; set; }
#endif
        /// <summary>An array of tabs that represents a collection of comments in a comment thread. For example, if a recipient has questions about the content of a document, they can add a comment to the document and control who else can see the comment. This value can&apos;t be set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CommentThread>? CommentThreadTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CommentThread> CommentThreadTabs { get; set; }
#endif
        /// <summary>A list of[Commission County tabs][cc].A Commission County tab displays the county of a notary&apos;s commission. This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary]. The tab&apos;s value can be edited by the recipient.[cc]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CommissionCounty>? CommissionCountyTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CommissionCounty> CommissionCountyTabs { get; set; }
#endif
        /// <summary>A list of[Commission Expiration tabs][tabref].A Commission Expiration tab displays the expiration date of a notary&apos;s commission. This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary]. The tab&apos;s value can be edited by the recipient.[tabref]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CommissionExpiration>? CommissionExpirationTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CommissionExpiration> CommissionExpirationTabs { get; set; }
#endif
        /// <summary>A list of[Commission Number tabs][tabref].A Commission Number tab displays a notary&apos;s commission number. This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary]. The tab&apos;s value can be edited by the recipient.[tabref]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CommissionNumber>? CommissionNumberTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CommissionNumber> CommissionNumberTabs { get; set; }
#endif
        /// <summary>A list of[Commission State tabs][cc].A Commission County tab displays the state in which a notary&apos;s commission was granted. This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary]. The tab&apos;s value can be edited by the recipient.[cc]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.CommissionState>? CommissionStateTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.CommissionState> CommissionStateTabs { get; set; }
#endif
        /// <summary>A list of[Company tabs][company].A Company tab displays a field for the name of the recipient&apos;s company. This value can&apos;t be set.[company]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/#parameters_company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Company>? CompanyTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Company> CompanyTabs { get; set; }
#endif
        /// <summary>A list of[Date Signed tabs][dateSigned].A Date Signed tab displays the date that the recipient signed the document. This value can&apos;t be set.[dateSigned]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.DateSigned>? DateSignedTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.DateSigned> DateSignedTabs { get; set; }
#endif
        /// <summary>A list of[Date tabs][date].A Date tab enables the recipient to enter a date. This value can&apos;t be set. The tooltip for this tab recommends the date format MM/DD/YYYY, but several other date formats are also accepted. The system retains the format that the recipient enters.**Note:** If you need to enforce a specific date format, Docusign recommends that you use a Text tab with a validation pattern and validation message.[date]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.DateObject>? DateTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.DateObject> DateTabs { get; set; }
#endif
        /// <summary>A list of[Decline tabs][decline].A Decline tab enables the recipient to decline the envelope. If the recipient clicks the tab during the signing process, the envelope is voided. The value of this tab can&apos;t be set.[decline]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Decline>? DeclineTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Decline> DeclineTabs { get; set; }
#endif
        /// <summary>A list of Draw Tabs.A Draw Tab allows the recipient to add a free-form drawing to the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Draw>? DrawTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Draw> DrawTabs { get; set; }
#endif
        /// <summary>A list of[Email Address tabs][emailAddress].An Email Address tab displays the recipient&apos;s email as entered in the recipient information. This value can&apos;t be set.[emailAddress]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.EmailAddress>? EmailAddressTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.EmailAddress> EmailAddressTabs { get; set; }
#endif
        /// <summary>A list of[Email tabs][email].An Email tab enables the recipient to enter an email address.This is a one-line field that checks that a valid emailaddress is entered. It uses the same parameters as a Texttab, with the validation message and pattern set for emailinformation. This value can be set.When getting information that includesthis tab type, the original value of the tab when theassociated envelope was sent is included in the response.[email]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Email>? EmailTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Email> EmailTabs { get; set; }
#endif
        /// <summary>A list of[Envelope ID tabs][envelopeId].An Envelope ID tab  displays the envelope ID. Recipients cannot enter or change the information in this tab. This value can&apos;t be set.[envelopeId]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/#response201_envelopeid</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.EnvelopeId>? EnvelopeIdTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.EnvelopeId> EnvelopeIdTabs { get; set; }
#endif
        /// <summary>A list of[First Name tabs][firstName].A First Name tab displays the recipient&apos;s first name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can&apos;t be set.[firstName]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/create/#parameters_firstname</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.FirstName>? FirstNameTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.FirstName> FirstNameTabs { get; set; }
#endif
        /// <summary>A list of [Formula tabs][formulaTab].The value of a Formula tab is calculated from the values of other number or date tabs in the document. When the recipient completes the underlying fields, the Formula tab calculates and displays the result. This value can be set.The `formula` property of the tab contains the references to the underlying tabs. To learn more about formulas, see [Calculated Fields][calculatedfields].If a Formula tab contains a `paymentDetails` property, the tab is considered a payment item. To learn more about payments, see [Requesting Payments Along with Signatures][paymentguide].[calculatedfields]: https://support.docusign.com/s/document-item?bundleId=gbo1643332197980&amp;topicId=crs1578456361259.html[paymentguide]:     https://support.docusign.com/s/document-item?bundleId=juu1573854950452&amp;topicId=fyw1573854935374.html[formulaTab]:       /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.FormulaTab>? FormulaTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.FormulaTab> FormulaTabs { get; set; }
#endif
        /// <summary>A list of[Full Name tabs][fullName].A Full Name tab displays the recipient&apos;s full name. This value can&apos;t be set.[fullName]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.FullName>? FullNameTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.FullName> FullNameTabs { get; set; }
#endif
        /// <summary>A list of[Initial Here tabs][initialHere].This type of tab enables the recipient to initial the document. May be optional. This value can&apos;t be set.[initialHere]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.InitialHere>? InitialHereTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.InitialHere> InitialHereTabs { get; set; }
#endif
        /// <summary>A list of[Last Name tabs][lastName].A Last Name tab displays the recipient&apos;s last name. The system automatically populates this field by splitting the name in the recipient information on spaces. This value can&apos;t be set.[lastName]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.LastName>? LastNameTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.LastName> LastNameTabs { get; set; }
#endif
        /// <summary>An array of List tabs.A List tab enables the recipient to choose from a list of options. You specify the options in the `listItems` property. This value can&apos;t be set.Find descriptions of all tab types inthe [EnvelopeRecipientTabs Resource][ert].[ert]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.List>? ListTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.List> ListTabs { get; set; }
#endif
        /// <summary>A list of  [Notarize tabs][notarize].A Notarize tab alerts notary recipients that they must take action on the page. This value can be set.**Note:** Only one notarize tab can appear on a page.[notarize]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Notarize>? NotarizeTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Notarize> NotarizeTabs { get; set; }
#endif
        /// <summary>A list of Notary Seal tabs.A Notary Seal tab enables the recipient to notarize a document. This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary].[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.NotarySeal>? NotarySealTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.NotarySeal> NotarySealTabs { get; set; }
#endif
        /// <summary>A list of[Note tabs][note].A Note tab displays additional information to the recipient in the form of a note. This value can be set.[note]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Note>? NoteTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Note> NoteTabs { get; set; }
#endif
        /// <summary>A list of Number tabs.Number tabs validate that the entered value is a number.They do not support advanced validation or display options.To learn more about the different forms of number tabs,see [Number fields](/docs/esign-rest-api/esign101/concepts/tabs/number-fields/) in the Concepts guide.For specific information about number tabssee [Features of numberTabs](/docs/esign-rest-api/esign101/concepts/tabs/number-fields/#features-of-numbertabs).[number]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Number>? NumberTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Number> NumberTabs { get; set; }
#endif
        /// <summary>A list of numerical tabs.Numerical  tabs provide robust display and validation features, including formatting for different regions and currencies, and minimum and maximum value validation.                                                                                                                                                                                                                                                                                                                                                                                                                                                             To learn more about the different forms of number tabs,see [Number fields](/docs/esign-rest-api/esign101/concepts/tabs/number-fields/) in the Concepts guide.For specific information about numerical tabssee [Features of numericalTabs](/docs/esign-rest-api/esign101/concepts/tabs/number-fields/#features-of-numericaltabs).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Numerical>? NumericalTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Numerical> NumericalTabs { get; set; }
#endif
        /// <summary>A list of[Phone Number tabs][cc].A Phone Number tab enables a recipient to enter a phone number.**Note:** This tab can only be assigned to a remote notary recipient using [Docusign Notary][notary].[cc]:  /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/[notary]: /docs/notary-api/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.PhoneNumber>? PhoneNumberTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.PhoneNumber> PhoneNumberTabs { get; set; }
#endif
        /// <summary>This type of tab enables the recipient to strike through document text. This value can&apos;t be set.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.PolyLineOverlay>? PolyLineOverlayTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.PolyLineOverlay> PolyLineOverlayTabs { get; set; }
#endif
        /// <summary>Prefill tabs are tabsthat the sender can fill inbefore the envelope is sent.They are sometimes calledsender tags or pre-fill fields.Only the following tab types can beprefill tabs:- text- check boxes- radio buttons[Pre-Fill Your Own Document Fields][app]describes how prefill tabswork in the web application.[Customize your envelopes with pre-fill fields][catblog]shows how to use prefill tabsin your application using the eSignatureSDKs.[app]:      https://support.docusign.com/s/document-item?bundleId=gbo1643332197980&amp;topicId=nwo1611173513994.html[catblog]:  https://www.docusign.com/blog/developers/common-api-tasks-customize-your-envelopes-pre-fill-fields</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PrefillTabs? PrefillTabs { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PrefillTabs PrefillTabs { get; set; }
#endif
        /// <summary>A list of [Radio Group tabs][radioGroup].A Radio Group tab places a group of radio buttons on a document. The `radios` property is used to add and place the radiobuttons associated with the group. Only one radio button can be selected in a group. This value can be set.[radioGroup]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.RadioGroup>? RadioGroupTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.RadioGroup> RadioGroupTabs { get; set; }
#endif
        /// <summary>A list of[Signer Attachment tabs][signerAttachment].This type of tab enables the recipient to attach supporting documents to an envelope. This value can&apos;t be set.[signerAttachment]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.SignerAttachment>? SignerAttachmentTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.SignerAttachment> SignerAttachmentTabs { get; set; }
#endif
        /// <summary>A list of[Sign Here tabs][signHere].This type of tab enables the recipient to sign a document. May be optional. This value can&apos;t be set.[signHere]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.SignHere>? SignHereTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.SignHere> SignHereTabs { get; set; }
#endif
        /// <summary>A list of [Smart Section](https://www.docusign.com/blog/dsdev-deep-dive-responsive-smart-sections) tabs.Smart Section tabs enhance responsive signing on mobile devices by enabling collapsible sections, page breaks, custom formatting options, and other advanced functionality.**Note:** Smart Sections are a premium feature. Responsive signing must also be enabled for your account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.SmartSection>? SmartSectionTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.SmartSection> SmartSectionTabs { get; set; }
#endif
        /// <summary>A list of[SSN tabs][ssn].An SSN tab contains a one-line field that enables the recipient to enter a Social Security Number (SSN) with or withoutdashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information. This value can be set.[ssn]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Ssn>? SsnTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Ssn> SsnTabs { get; set; }
#endif
        /// <summary>An array of `tabGroup` items.To associate a tab with a tab group, add the tab group&apos;s `groupLabel` to the tab&apos;s `tabGroupLabels` array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.TabGroup>? TabGroups { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.TabGroup> TabGroups { get; set; }
#endif
        /// <summary>A list ofText tabs.A text tab enables the recipient to enter free text. This value can be set.Find descriptions of all tab types inthe [EnvelopeRecipientTabs Resource][ert].[ert]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Text>? TextTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Text> TextTabs { get; set; }
#endif
        /// <summary>A list of[Title tabs][title].A Title tab displays the recipient&apos;s title.  This value can&apos;t be set.[title]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Title>? TitleTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Title> TitleTabs { get; set; }
#endif
        /// <summary>A list of[View tabs][view].A View tab is used with an Approve tab to handle supplemental documents.  This value can be set.[view]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.View>? ViewTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.View> ViewTabs { get; set; }
#endif
        /// <summary>A list of[Zip tabs][zip].A Zip tab enables the recipient to enter a ZIP code. The ZIP code can be five digits or nine digits ( in ZIP+4 format), and can be entered with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for ZIP code information.  This value can be set.[zip]: /docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Zip>? ZipTabs { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Zip> ZipTabs { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.EnvelopeDocumentTabs"/> and sets the default values.
        /// </summary>
        public EnvelopeDocumentTabs()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.EnvelopeDocumentTabs"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.EnvelopeDocumentTabs CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.EnvelopeDocumentTabs();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approveTabs", n => { ApproveTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Approve>(global::DocuSignKiota.Client.Models.Approve.CreateFromDiscriminatorValue)?.AsList(); } },
                { "checkboxTabs", n => { CheckboxTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Checkbox>(global::DocuSignKiota.Client.Models.Checkbox.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commentThreadTabs", n => { CommentThreadTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommentThread>(global::DocuSignKiota.Client.Models.CommentThread.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionCountyTabs", n => { CommissionCountyTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionCounty>(global::DocuSignKiota.Client.Models.CommissionCounty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionExpirationTabs", n => { CommissionExpirationTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionExpiration>(global::DocuSignKiota.Client.Models.CommissionExpiration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionNumberTabs", n => { CommissionNumberTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionNumber>(global::DocuSignKiota.Client.Models.CommissionNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commissionStateTabs", n => { CommissionStateTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionState>(global::DocuSignKiota.Client.Models.CommissionState.CreateFromDiscriminatorValue)?.AsList(); } },
                { "companyTabs", n => { CompanyTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Company>(global::DocuSignKiota.Client.Models.Company.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dateSignedTabs", n => { DateSignedTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.DateSigned>(global::DocuSignKiota.Client.Models.DateSigned.CreateFromDiscriminatorValue)?.AsList(); } },
                { "dateTabs", n => { DateTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.DateObject>(global::DocuSignKiota.Client.Models.DateObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "declineTabs", n => { DeclineTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Decline>(global::DocuSignKiota.Client.Models.Decline.CreateFromDiscriminatorValue)?.AsList(); } },
                { "drawTabs", n => { DrawTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Draw>(global::DocuSignKiota.Client.Models.Draw.CreateFromDiscriminatorValue)?.AsList(); } },
                { "emailAddressTabs", n => { EmailAddressTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.EmailAddress>(global::DocuSignKiota.Client.Models.EmailAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "emailTabs", n => { EmailTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Email>(global::DocuSignKiota.Client.Models.Email.CreateFromDiscriminatorValue)?.AsList(); } },
                { "envelopeIdTabs", n => { EnvelopeIdTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.EnvelopeId>(global::DocuSignKiota.Client.Models.EnvelopeId.CreateFromDiscriminatorValue)?.AsList(); } },
                { "firstNameTabs", n => { FirstNameTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FirstName>(global::DocuSignKiota.Client.Models.FirstName.CreateFromDiscriminatorValue)?.AsList(); } },
                { "formulaTabs", n => { FormulaTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FormulaTab>(global::DocuSignKiota.Client.Models.FormulaTab.CreateFromDiscriminatorValue)?.AsList(); } },
                { "fullNameTabs", n => { FullNameTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FullName>(global::DocuSignKiota.Client.Models.FullName.CreateFromDiscriminatorValue)?.AsList(); } },
                { "initialHereTabs", n => { InitialHereTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.InitialHere>(global::DocuSignKiota.Client.Models.InitialHere.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lastNameTabs", n => { LastNameTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.LastName>(global::DocuSignKiota.Client.Models.LastName.CreateFromDiscriminatorValue)?.AsList(); } },
                { "listTabs", n => { ListTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.List>(global::DocuSignKiota.Client.Models.List.CreateFromDiscriminatorValue)?.AsList(); } },
                { "notarizeTabs", n => { NotarizeTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Notarize>(global::DocuSignKiota.Client.Models.Notarize.CreateFromDiscriminatorValue)?.AsList(); } },
                { "notarySealTabs", n => { NotarySealTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.NotarySeal>(global::DocuSignKiota.Client.Models.NotarySeal.CreateFromDiscriminatorValue)?.AsList(); } },
                { "noteTabs", n => { NoteTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Note>(global::DocuSignKiota.Client.Models.Note.CreateFromDiscriminatorValue)?.AsList(); } },
                { "numberTabs", n => { NumberTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Number>(global::DocuSignKiota.Client.Models.Number.CreateFromDiscriminatorValue)?.AsList(); } },
                { "numericalTabs", n => { NumericalTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Numerical>(global::DocuSignKiota.Client.Models.Numerical.CreateFromDiscriminatorValue)?.AsList(); } },
                { "phoneNumberTabs", n => { PhoneNumberTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PhoneNumber>(global::DocuSignKiota.Client.Models.PhoneNumber.CreateFromDiscriminatorValue)?.AsList(); } },
                { "polyLineOverlayTabs", n => { PolyLineOverlayTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PolyLineOverlay>(global::DocuSignKiota.Client.Models.PolyLineOverlay.CreateFromDiscriminatorValue)?.AsList(); } },
                { "prefillTabs", n => { PrefillTabs = n.GetObjectValue<global::DocuSignKiota.Client.Models.PrefillTabs>(global::DocuSignKiota.Client.Models.PrefillTabs.CreateFromDiscriminatorValue); } },
                { "radioGroupTabs", n => { RadioGroupTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.RadioGroup>(global::DocuSignKiota.Client.Models.RadioGroup.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signHereTabs", n => { SignHereTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SignHere>(global::DocuSignKiota.Client.Models.SignHere.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signerAttachmentTabs", n => { SignerAttachmentTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SignerAttachment>(global::DocuSignKiota.Client.Models.SignerAttachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "smartSectionTabs", n => { SmartSectionTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SmartSection>(global::DocuSignKiota.Client.Models.SmartSection.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ssnTabs", n => { SsnTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Ssn>(global::DocuSignKiota.Client.Models.Ssn.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tabGroups", n => { TabGroups = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.TabGroup>(global::DocuSignKiota.Client.Models.TabGroup.CreateFromDiscriminatorValue)?.AsList(); } },
                { "textTabs", n => { TextTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Text>(global::DocuSignKiota.Client.Models.Text.CreateFromDiscriminatorValue)?.AsList(); } },
                { "titleTabs", n => { TitleTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Title>(global::DocuSignKiota.Client.Models.Title.CreateFromDiscriminatorValue)?.AsList(); } },
                { "viewTabs", n => { ViewTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.View>(global::DocuSignKiota.Client.Models.View.CreateFromDiscriminatorValue)?.AsList(); } },
                { "zipTabs", n => { ZipTabs = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Zip>(global::DocuSignKiota.Client.Models.Zip.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Approve>("approveTabs", ApproveTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Checkbox>("checkboxTabs", CheckboxTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommentThread>("commentThreadTabs", CommentThreadTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionCounty>("commissionCountyTabs", CommissionCountyTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionExpiration>("commissionExpirationTabs", CommissionExpirationTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionNumber>("commissionNumberTabs", CommissionNumberTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.CommissionState>("commissionStateTabs", CommissionStateTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Company>("companyTabs", CompanyTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.DateSigned>("dateSignedTabs", DateSignedTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.DateObject>("dateTabs", DateTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Decline>("declineTabs", DeclineTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Draw>("drawTabs", DrawTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.EmailAddress>("emailAddressTabs", EmailAddressTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Email>("emailTabs", EmailTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.EnvelopeId>("envelopeIdTabs", EnvelopeIdTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FirstName>("firstNameTabs", FirstNameTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FormulaTab>("formulaTabs", FormulaTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.FullName>("fullNameTabs", FullNameTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.InitialHere>("initialHereTabs", InitialHereTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.LastName>("lastNameTabs", LastNameTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.List>("listTabs", ListTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Notarize>("notarizeTabs", NotarizeTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.NotarySeal>("notarySealTabs", NotarySealTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Note>("noteTabs", NoteTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Number>("numberTabs", NumberTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Numerical>("numericalTabs", NumericalTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PhoneNumber>("phoneNumberTabs", PhoneNumberTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PolyLineOverlay>("polyLineOverlayTabs", PolyLineOverlayTabs);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PrefillTabs>("prefillTabs", PrefillTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.RadioGroup>("radioGroupTabs", RadioGroupTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SignerAttachment>("signerAttachmentTabs", SignerAttachmentTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SignHere>("signHereTabs", SignHereTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SmartSection>("smartSectionTabs", SmartSectionTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Ssn>("ssnTabs", SsnTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.TabGroup>("tabGroups", TabGroups);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Text>("textTabs", TextTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Title>("titleTabs", TitleTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.View>("viewTabs", ViewTabs);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Zip>("zipTabs", ZipTabs);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
