// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnvelopeViewTaggerSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When `paletteSections` is set to `custom`, this property selects the default tagger palette. Valid values:  * `custom`* `merge`* `notary`* `seals`* `smartContracts`* `annotations`* `smartSections`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaletteDefault { get; set; }
#nullable restore
#else
        public string PaletteDefault { get; set; }
#endif
        /// <summary>Valid values:* `default` (default): The default tagger palette UX* `none`: No tagger palette* `custom`: Set by `paletteDefault`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaletteSections { get; set; }
#nullable restore
#else
        public string PaletteSections { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PaletteSettings? PaletteSettings { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PaletteSettings PaletteSettings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.EnvelopeViewTaggerSettings"/> and sets the default values.
        /// </summary>
        public EnvelopeViewTaggerSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.EnvelopeViewTaggerSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.EnvelopeViewTaggerSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.EnvelopeViewTaggerSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "paletteDefault", n => { PaletteDefault = n.GetStringValue(); } },
                { "paletteSections", n => { PaletteSections = n.GetStringValue(); } },
                { "paletteSettings", n => { PaletteSettings = n.GetObjectValue<global::DocuSignKiota.Client.Models.PaletteSettings>(global::DocuSignKiota.Client.Models.PaletteSettings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("paletteDefault", PaletteDefault);
            writer.WriteStringValue("paletteSections", PaletteSections);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PaletteSettings>("paletteSettings", PaletteSettings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
