// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Object representing a new user.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NewUser : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Contains a token that can be used for authentication in API calls instead of using the user name and password.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApiPassword { get; set; }
#nullable restore
#else
        public string ApiPassword { get; set; }
#endif
        /// <summary>The UTC DateTime when the item was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedDateTime { get; set; }
#nullable restore
#else
        public string CreatedDateTime { get; set; }
#endif
        /// <summary>The user&apos;s email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>The licenseStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicenseStatus { get; set; }
#nullable restore
#else
        public string LicenseStatus { get; set; }
#endif
        /// <summary>The licenseType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicenseType { get; set; }
#nullable restore
#else
        public string LicenseType { get; set; }
#endif
        /// <summary>The user&apos;s membership ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MembershipId { get; set; }
#nullable restore
#else
        public string MembershipId { get; set; }
#endif
        /// <summary>The ID of the permission profile.Use [AccountPermissionProfiles: list](/docs/esign-rest-api/reference/accounts/accountpermissionprofiles/list/)to get a list of permission profiles and their IDs.You can also download a CSV file of all permission profilesand their IDs from the **Settings &gt; Permission Profiles** pageof your eSignature account page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionProfileId { get; set; }
#nullable restore
#else
        public string PermissionProfileId { get; set; }
#endif
        /// <summary>The name of the account permission profile. Example: `Account Administrator`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionProfileName { get; set; }
#nullable restore
#else
        public string PermissionProfileName { get; set; }
#endif
        /// <summary>A URI containing the user ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>Specifies the user ID for the new user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>The name of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserName { get; set; }
#nullable restore
#else
        public string UserName { get; set; }
#endif
        /// <summary>Status of the user&apos;s account. One of:- `ActivationRequired`- `ActivationSent`- `Active`- `Closed`- `Disabled`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserStatus { get; set; }
#nullable restore
#else
        public string UserStatus { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.NewUser"/> and sets the default values.
        /// </summary>
        public NewUser()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.NewUser"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.NewUser CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.NewUser();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "apiPassword", n => { ApiPassword = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "licenseStatus", n => { LicenseStatus = n.GetStringValue(); } },
                { "licenseType", n => { LicenseType = n.GetStringValue(); } },
                { "membershipId", n => { MembershipId = n.GetStringValue(); } },
                { "permissionProfileId", n => { PermissionProfileId = n.GetStringValue(); } },
                { "permissionProfileName", n => { PermissionProfileName = n.GetStringValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
                { "userName", n => { UserName = n.GetStringValue(); } },
                { "userStatus", n => { UserStatus = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("apiPassword", ApiPassword);
            writer.WriteStringValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("licenseStatus", LicenseStatus);
            writer.WriteStringValue("licenseType", LicenseType);
            writer.WriteStringValue("membershipId", MembershipId);
            writer.WriteStringValue("permissionProfileId", PermissionProfileId);
            writer.WriteStringValue("permissionProfileName", PermissionProfileName);
            writer.WriteStringValue("uri", Uri);
            writer.WriteStringValue("userId", UserId);
            writer.WriteStringValue("userName", UserName);
            writer.WriteStringValue("userStatus", UserStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
