// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Contains details about a PowerForm.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PowerForm : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ID of the user who created the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The UTC DateTime when the item was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedDateTime { get; set; }
#nullable restore
#else
        public string CreatedDateTime { get; set; }
#endif
        /// <summary>The body of the email message sent to the recipients. Maximum length: 10000 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailBody { get; set; }
#nullable restore
#else
        public string EmailBody { get; set; }
#endif
        /// <summary>The subject line of the email message that is sent to all recipients.For information about adding merge field information to the email subject, see [Template Email Subject Merge Fields](/docs/esign-rest-api/reference/templates/templates/create/#template-email-subject-merge-fields).**Note:** The subject line is limited to 100 characters, including any merged fields.It is not truncated. It is an error if the text is longer than 100 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailSubject { get; set; }
#nullable restore
#else
        public string EmailSubject { get; set; }
#endif
        /// <summary>The envelopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.Envelope>? Envelopes { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.Envelope> Envelopes { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>The instructions that display on the landing page for the first recipient. These instructions are important if the recipient accesses the PowerForm by a method other than email. If instructions are entered, they display as an introduction after the recipient accesses the PowerForm.  Limit: 2000 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Instructions { get; set; }
#nullable restore
#else
        public string Instructions { get; set; }
#endif
        /// <summary>When **true,** indicates that the PowerForm is active and can be sent to recipients. This is the default value.When **false,** the PowerForm cannot be emailed or accessed by a recipient, even if they arrive at the PowerForm URL. If a recipient attempts to sign an inactive PowerForm, an error message informs the recipient that the document is not active and suggests that they contact the sender.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IsActive { get; set; }
#nullable restore
#else
        public string IsActive { get; set; }
#endif
        /// <summary>The UTC DateTime when the PowerForm was last used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastUsed { get; set; }
#nullable restore
#else
        public string LastUsed { get; set; }
#endif
        /// <summary>The length of time before the same recipient can sign the same PowerForm. This property is used in combination with the `limitUseIntervalUnits` property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LimitUseInterval { get; set; }
#nullable restore
#else
        public string LimitUseInterval { get; set; }
#endif
        /// <summary>When **true,** the `limitUseInterval` is enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LimitUseIntervalEnabled { get; set; }
#nullable restore
#else
        public string LimitUseIntervalEnabled { get; set; }
#endif
        /// <summary>The units associated with the `limitUseInterval`. Valid values are:- `minutes`- `hours- `days`- `weeks`- `months`For example, to limit a recipient to signing once per year, set the `limitUseInterval` to 365 and the `limitUseIntervalUnits` to `days`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LimitUseIntervalUnits { get; set; }
#nullable restore
#else
        public string LimitUseIntervalUnits { get; set; }
#endif
        /// <summary>When **true,** you can set a maximum number of uses for the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxUseEnabled { get; set; }
#nullable restore
#else
        public string MaxUseEnabled { get; set; }
#endif
        /// <summary>The name of the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerFormId { get; set; }
#nullable restore
#else
        public string PowerFormId { get; set; }
#endif
        /// <summary>The URL for the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PowerFormUrl { get; set; }
#nullable restore
#else
        public string PowerFormUrl { get; set; }
#endif
        /// <summary>An array of recipient objects that provides details about the recipients of the envelope.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.PowerFormRecipient>? Recipients { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.PowerFormRecipient> Recipients { get; set; }
#endif
        /// <summary>The sender&apos;s name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderName { get; set; }
#nullable restore
#else
        public string SenderName { get; set; }
#endif
        /// <summary>The ID of the sender.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderUserId { get; set; }
#nullable restore
#else
        public string SenderUserId { get; set; }
#endif
        /// <summary>The signing mode to use. Valid values are: - `email`: Verifies the recipient&apos;s identity using email authentication before the recipient can sign a document. The recipient enters their email address and then clicks **Begin Signing** to begin the signing process. The system then sends an email message with a validation code for the PowerForm to the recipient. If the recipient does not provide a valid email address, they cannot open and sign the document.  - `direct`: Does not require any verification. After a recipient enters their email address and clicks **Begin Signing,** a new browser tab opens and the recipient can immediately begin the signing process. Because the recipient&apos;s identity is not verified by using email authentication, we strongly recommend that you only use the `direct` signing mode when the PowerForm is accessible behind a secure portal where the recipient&apos;s identity is already authenticated, or where another form of authentication is specified for the recipient in the Docusign template (for example, an access code, phone authentication, or ID check).  **Note:** In the account settings, `enablePowerFormDirect` must be **true** to use `direct` as the `signingMode`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningMode { get; set; }
#nullable restore
#else
        public string SigningMode { get; set; }
#endif
        /// <summary>The ID of the template used to create the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>The name of the template used to create the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateName { get; set; }
#nullable restore
#else
        public string TemplateName { get; set; }
#endif
        /// <summary>The number of times the PowerForm has been used. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimesUsed { get; set; }
#nullable restore
#else
        public string TimesUsed { get; set; }
#endif
        /// <summary>The URI for the PowerForm.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>The number of times the PowerForm can still be used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsesRemaining { get; set; }
#nullable restore
#else
        public string UsesRemaining { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.PowerForm"/> and sets the default values.
        /// </summary>
        public PowerForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.PowerForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.PowerForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.PowerForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetStringValue(); } },
                { "emailBody", n => { EmailBody = n.GetStringValue(); } },
                { "emailSubject", n => { EmailSubject = n.GetStringValue(); } },
                { "envelopes", n => { Envelopes = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Envelope>(global::DocuSignKiota.Client.Models.Envelope.CreateFromDiscriminatorValue)?.AsList(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "instructions", n => { Instructions = n.GetStringValue(); } },
                { "isActive", n => { IsActive = n.GetStringValue(); } },
                { "lastUsed", n => { LastUsed = n.GetStringValue(); } },
                { "limitUseInterval", n => { LimitUseInterval = n.GetStringValue(); } },
                { "limitUseIntervalEnabled", n => { LimitUseIntervalEnabled = n.GetStringValue(); } },
                { "limitUseIntervalUnits", n => { LimitUseIntervalUnits = n.GetStringValue(); } },
                { "maxUseEnabled", n => { MaxUseEnabled = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "powerFormId", n => { PowerFormId = n.GetStringValue(); } },
                { "powerFormUrl", n => { PowerFormUrl = n.GetStringValue(); } },
                { "recipients", n => { Recipients = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PowerFormRecipient>(global::DocuSignKiota.Client.Models.PowerFormRecipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "senderName", n => { SenderName = n.GetStringValue(); } },
                { "senderUserId", n => { SenderUserId = n.GetStringValue(); } },
                { "signingMode", n => { SigningMode = n.GetStringValue(); } },
                { "templateId", n => { TemplateId = n.GetStringValue(); } },
                { "templateName", n => { TemplateName = n.GetStringValue(); } },
                { "timesUsed", n => { TimesUsed = n.GetStringValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
                { "usesRemaining", n => { UsesRemaining = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("emailBody", EmailBody);
            writer.WriteStringValue("emailSubject", EmailSubject);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.Envelope>("envelopes", Envelopes);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("instructions", Instructions);
            writer.WriteStringValue("isActive", IsActive);
            writer.WriteStringValue("lastUsed", LastUsed);
            writer.WriteStringValue("limitUseInterval", LimitUseInterval);
            writer.WriteStringValue("limitUseIntervalEnabled", LimitUseIntervalEnabled);
            writer.WriteStringValue("limitUseIntervalUnits", LimitUseIntervalUnits);
            writer.WriteStringValue("maxUseEnabled", MaxUseEnabled);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("powerFormId", PowerFormId);
            writer.WriteStringValue("powerFormUrl", PowerFormUrl);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.PowerFormRecipient>("recipients", Recipients);
            writer.WriteStringValue("senderName", SenderName);
            writer.WriteStringValue("senderUserId", SenderUserId);
            writer.WriteStringValue("signingMode", SigningMode);
            writer.WriteStringValue("templateId", TemplateId);
            writer.WriteStringValue("templateName", TemplateName);
            writer.WriteStringValue("timesUsed", TimesUsed);
            writer.WriteStringValue("uri", Uri);
            writer.WriteStringValue("usesRemaining", UsesRemaining);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
