// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// One of the selectable radio buttonsin the `radios` propertyof a [`radioGroup`](/docs/esign-rest-api/reference/envelopes/enveloperecipienttabs/) tab.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Radio : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When **true,** the text string in the document may have extra whitespace and still match the anchor string. This occurs in two cases.First, it matches if the document string has a single extra whitespace character following a non-whitespace character in the anchor string. For example, if the anchor string is `DocuSign`, then `Docu Sign` will match. However, &lt;code&gt;Docu&amp;nbsp;&amp;nbsp;&amp;nbsp;Sign&lt;/code&gt; will not match.Second, it matches if the document string has one or more extra whitespace characters following a whitespace character in the anchor string. For example, if the anchor string is `Docu Sign`, then &lt;code&gt;Docu&amp;nbsp;&amp;nbsp;&amp;nbsp;Sign&lt;/code&gt; will match.The default value is **true.**</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorAllowWhiteSpaceInCharacters { get; set; }
#nullable restore
#else
        public string AnchorAllowWhiteSpaceInCharacters { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorAllowWhiteSpaceInCharactersMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorAllowWhiteSpaceInCharactersMetadata { get; set; }
#endif
        /// <summary>This property controls how [anchor tabs][AnchorTabs] are placed. When **true,** the text string in a document must match the case of the `anchorString` property for an anchor tab to be created. The default value is **false.**For example, when set to **true,** if the anchor string is `DocuSign`, then `DocuSign` will match but `Docusign`, `docusign`, `DoCuSiGn`, etc. will not match. When **false,** `DocuSign`, `Docusign`, `docusign`, `DoCuSiGn`, etc. will all match.This functionality uses the following rules:- Unless punctuation is specified in the `anchorString`, this functionality ignores punctuation and the following characters:  $~&gt;&lt;|^+=  For example, the `anchorString` `water` will match on the string `Fetch a pail of water.`- Strings embedded in other strings are ignored during the matching process.- In words that have dashes, the parts separated by dashes are treated as distinct words.  Example: If the anchor string is `forget`, then an anchor tab is placed on the `forget` in `forget-me-not`, even when `anchorMatchWholeWord` is set to **true.**- Letters with accent marks are treated as distinct characters from their unaccented counterparts.- For single-character anchor strings, if the two characters appear right next to each other in the document, a single anchor tab is placed for both of them.  Example: If the anchor string is `i`, then only one anchor tab is placed in `skiing`.- Unlike punctuation, numbers are not ignored when finding anchor words.  Example: If the anchor string is `cat`, then `-cat-` is matched but `1cat2` is not when `anchorMatchWholeWord` is set to **true** (its default value).**Note:** You can only specify the value of this property in POST requests.[AnchorTabs]: /docs/esign-rest-api/esign101/concepts/tabs/auto-place/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorCaseSensitive { get; set; }
#nullable restore
#else
        public string AnchorCaseSensitive { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorCaseSensitiveMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorCaseSensitiveMetadata { get; set; }
#endif
        /// <summary>This property controls how [anchor tabs][AnchorTabs] are aligned in relation to the anchor text. Possible values are :- `left`: Aligns the left side of the tab with the beginning of the first character of the matching anchor word. This is the default value.- `right`: Aligns the tab’s left side with the last character of the matching anchor word.**Note:** You can only specify the value of this property in POST requests.[AnchorTabs]: /docs/esign-rest-api/esign101/concepts/tabs/auto-place/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorHorizontalAlignment { get; set; }
#nullable restore
#else
        public string AnchorHorizontalAlignment { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorHorizontalAlignmentMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorHorizontalAlignmentMetadata { get; set; }
#endif
        /// <summary>When **true,** this tab is ignored if the `anchorString` is not found in the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorIgnoreIfNotPresent { get; set; }
#nullable restore
#else
        public string AnchorIgnoreIfNotPresent { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorIgnoreIfNotPresentMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorIgnoreIfNotPresentMetadata { get; set; }
#endif
        /// <summary>When **true,** the text string in a document must match the value of the `anchorString` property in its entirety for an [anchor tab][AnchorTab] to be created. The default value is **false.**For example, when set to **true,** if the input is `man` then `man` will match but `manpower`, `fireman`, and `penmanship` will not. When **false,** if the input is `man` then `man`, `manpower`, `fireman`, and `penmanship` will all match.This functionality uses the following rules:- Unless punctuation is specified in the `anchorString`, this functionality ignores punctuation and the following characters:  $~&gt;&lt;|^+=  For example, the `anchorString` `water` will match on the string `Fetch a pail of water.`- Strings embedded in other strings are ignored during the matching process.- In words that have dashes, the parts separated by dashes are treated as distinct words.  Example: If the anchor string is `forget`, then an anchor tab is placed on the `forget` in `forget-me-not`, even when `anchorMatchWholeWord` is set to **true.**- Letters with accent marks are treated as distinct characters from their unaccented counterparts.- For single-character anchor strings, if the two characters appear right next to each other in the document, a single anchor tab is placed for both of them.  Example: If the anchor string is `i`, then only one anchor tab is placed in `skiing`.- Unlike punctuation, numbers are not ignored when finding anchor words.  Example: If the anchor string is `cat`, then `-cat-` is matched but `1cat2` is not when `anchorMatchWholeWord` is set to **true** (its default value).**Note:** You can only specify the value of this property in POST requests.[AnchorTab]: /docs/esign-rest-api/esign101/concepts/tabs/auto-place/</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorMatchWholeWord { get; set; }
#nullable restore
#else
        public string AnchorMatchWholeWord { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorMatchWholeWordMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorMatchWholeWordMetadata { get; set; }
#endif
        /// <summary>Specifies the string to find in the document and use as the basis for tab placement.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorString { get; set; }
#nullable restore
#else
        public string AnchorString { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorStringMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorStringMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorTabProcessorVersion { get; set; }
#nullable restore
#else
        public string AnchorTabProcessorVersion { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorTabProcessorVersionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorTabProcessorVersionMetadata { get; set; }
#endif
        /// <summary>Specifies units of the `anchorXOffset` and `anchorYOffset`. Valid units are:- `pixels` (default)- `inches`- `mms`- `cms`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorUnits { get; set; }
#nullable restore
#else
        public string AnchorUnits { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorUnitsMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorUnitsMetadata { get; set; }
#endif
        /// <summary>Specifies the X axis location of the tab in `anchorUnits` relative to the `anchorString`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorXOffset { get; set; }
#nullable restore
#else
        public string AnchorXOffset { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorXOffsetMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorXOffsetMetadata { get; set; }
#endif
        /// <summary>Specifies the Y axis location of the tab in `anchorUnits` relative to the `anchorString`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AnchorYOffset { get; set; }
#nullable restore
#else
        public string AnchorYOffset { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? AnchorYOffsetMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata AnchorYOffsetMetadata { get; set; }
#endif
        /// <summary>When **true,** the information in the tab is bold.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bold { get; set; }
#nullable restore
#else
        public string Bold { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? BoldMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata BoldMetadata { get; set; }
#endif
        /// <summary>The caption property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Caption { get; set; }
#nullable restore
#else
        public string Caption { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? CaptionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata CaptionMetadata { get; set; }
#endif
        /// <summary>The connectedObjectDetails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ConnectedObjectDetails? ConnectedObjectDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ConnectedObjectDetails ConnectedObjectDetails { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>The extensionData property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ExtensionData? ExtensionData { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ExtensionData ExtensionData { get; set; }
#endif
        /// <summary>The font to be used for the tab value. Supported fonts include:- Default- Arial- ArialNarrow- Calibri- CourierNew- Garamond- Georgia- Helvetica- LucidaConsole- MSGothic- MSMincho- OCR-A- Tahoma- TimesNewRoman- Trebuchet- Verdana</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Font { get; set; }
#nullable restore
#else
        public string Font { get; set; }
#endif
        /// <summary>The font color to use for the information in the tab. Possible values are: - Black- BrightBlue- BrightRed- DarkGreen- DarkRed- Gold- Green- NavyBlue- Purple- White</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontColor { get; set; }
#nullable restore
#else
        public string FontColor { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? FontColorMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata FontColorMetadata { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? FontMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata FontMetadata { get; set; }
#endif
        /// <summary>The font size used for the information in the tab. Possible values are:- Size7- Size8- Size9- Size10- Size11- Size12- Size14- Size16- Size18- Size20- Size22- Size24- Size26- Size28- Size36- Size48- Size72</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FontSize { get; set; }
#nullable restore
#else
        public string FontSize { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? FontSizeMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata FontSizeMetadata { get; set; }
#endif
        /// <summary>When **true,** the information in the tab is italic.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Italic { get; set; }
#nullable restore
#else
        public string Italic { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? ItalicMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata ItalicMetadata { get; set; }
#endif
        /// <summary>When **true,** the signer cannot change the data of the custom tab.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locked { get; set; }
#nullable restore
#else
        public string Locked { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? LockedMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata LockedMetadata { get; set; }
#endif
        /// <summary>Reserved for Docusign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MergeFieldXml { get; set; }
#nullable restore
#else
        public string MergeFieldXml { get; set; }
#endif
        /// <summary>Specifies the page number on which the tab is located.Must be 1 for supplemental documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PageNumber { get; set; }
#nullable restore
#else
        public string PageNumber { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? PageNumberMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata PageNumberMetadata { get; set; }
#endif
        /// <summary>When **true,** the signer is required to fill out this tab.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Required { get; set; }
#nullable restore
#else
        public string Required { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? RequiredMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata RequiredMetadata { get; set; }
#endif
        /// <summary>When **true,** the radio button is selected.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Selected { get; set; }
#nullable restore
#else
        public string Selected { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? SelectedMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata SelectedMetadata { get; set; }
#endif
        /// <summary>Indicates the envelope status. Valid values are:* sent - The envelope is sent to the recipients. * created - The envelope is saved as a draft and can be modified and sent later.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? StatusMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata StatusMetadata { get; set; }
#endif
        /// <summary>The tabFullyQualifiedPath property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TabFullyQualifiedPath { get; set; }
#nullable restore
#else
        public string TabFullyQualifiedPath { get; set; }
#endif
        /// <summary>The unique identifier for the tab.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TabId { get; set; }
#nullable restore
#else
        public string TabId { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? TabIdMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata TabIdMetadata { get; set; }
#endif
        /// <summary>A positive integer that sets the order the tab is navigated to during signing.Tabs on a page are navigated to in ascending order, starting with the lowest number and moving to the highest. If two or more tabs have the same `tabOrder` value, the normal auto-navigation setting behavior for the envelope is used.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TabOrder { get; set; }
#nullable restore
#else
        public string TabOrder { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? TabOrderMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata TabOrderMetadata { get; set; }
#endif
        /// <summary>When **true,** the information in the tab is underlined.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Underline { get; set; }
#nullable restore
#else
        public string Underline { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? UnderlineMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata UnderlineMetadata { get; set; }
#endif
        /// <summary>Specifies the value of the tab. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? ValueMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata ValueMetadata { get; set; }
#endif
        /// <summary>This property indicates the horizontal offset of the object on the page.Docusign uses 72 DPI when determining position.Required. Must be an integer. May be zero.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? XPosition { get; set; }
#nullable restore
#else
        public string XPosition { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? XPositionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata XPositionMetadata { get; set; }
#endif
        /// <summary>This property indicates the vertical offset of the object on the page.Docusign uses 72 DPI when determining position.Required. Must be an integer. May be zero.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? YPosition { get; set; }
#nullable restore
#else
        public string YPosition { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? YPositionMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata YPositionMetadata { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.Radio"/> and sets the default values.
        /// </summary>
        public Radio()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.Radio"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.Radio CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.Radio();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "anchorAllowWhiteSpaceInCharacters", n => { AnchorAllowWhiteSpaceInCharacters = n.GetStringValue(); } },
                { "anchorAllowWhiteSpaceInCharactersMetadata", n => { AnchorAllowWhiteSpaceInCharactersMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorCaseSensitive", n => { AnchorCaseSensitive = n.GetStringValue(); } },
                { "anchorCaseSensitiveMetadata", n => { AnchorCaseSensitiveMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorHorizontalAlignment", n => { AnchorHorizontalAlignment = n.GetStringValue(); } },
                { "anchorHorizontalAlignmentMetadata", n => { AnchorHorizontalAlignmentMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorIgnoreIfNotPresent", n => { AnchorIgnoreIfNotPresent = n.GetStringValue(); } },
                { "anchorIgnoreIfNotPresentMetadata", n => { AnchorIgnoreIfNotPresentMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorMatchWholeWord", n => { AnchorMatchWholeWord = n.GetStringValue(); } },
                { "anchorMatchWholeWordMetadata", n => { AnchorMatchWholeWordMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorString", n => { AnchorString = n.GetStringValue(); } },
                { "anchorStringMetadata", n => { AnchorStringMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorTabProcessorVersion", n => { AnchorTabProcessorVersion = n.GetStringValue(); } },
                { "anchorTabProcessorVersionMetadata", n => { AnchorTabProcessorVersionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorUnits", n => { AnchorUnits = n.GetStringValue(); } },
                { "anchorUnitsMetadata", n => { AnchorUnitsMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorXOffset", n => { AnchorXOffset = n.GetStringValue(); } },
                { "anchorXOffsetMetadata", n => { AnchorXOffsetMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "anchorYOffset", n => { AnchorYOffset = n.GetStringValue(); } },
                { "anchorYOffsetMetadata", n => { AnchorYOffsetMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "bold", n => { Bold = n.GetStringValue(); } },
                { "boldMetadata", n => { BoldMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "caption", n => { Caption = n.GetStringValue(); } },
                { "captionMetadata", n => { CaptionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "connectedObjectDetails", n => { ConnectedObjectDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ConnectedObjectDetails>(global::DocuSignKiota.Client.Models.ConnectedObjectDetails.CreateFromDiscriminatorValue); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "extensionData", n => { ExtensionData = n.GetObjectValue<global::DocuSignKiota.Client.Models.ExtensionData>(global::DocuSignKiota.Client.Models.ExtensionData.CreateFromDiscriminatorValue); } },
                { "font", n => { Font = n.GetStringValue(); } },
                { "fontColor", n => { FontColor = n.GetStringValue(); } },
                { "fontColorMetadata", n => { FontColorMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "fontMetadata", n => { FontMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "fontSize", n => { FontSize = n.GetStringValue(); } },
                { "fontSizeMetadata", n => { FontSizeMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "italic", n => { Italic = n.GetStringValue(); } },
                { "italicMetadata", n => { ItalicMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "locked", n => { Locked = n.GetStringValue(); } },
                { "lockedMetadata", n => { LockedMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "mergeFieldXml", n => { MergeFieldXml = n.GetStringValue(); } },
                { "pageNumber", n => { PageNumber = n.GetStringValue(); } },
                { "pageNumberMetadata", n => { PageNumberMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "required", n => { Required = n.GetStringValue(); } },
                { "requiredMetadata", n => { RequiredMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "selected", n => { Selected = n.GetStringValue(); } },
                { "selectedMetadata", n => { SelectedMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "statusMetadata", n => { StatusMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "tabFullyQualifiedPath", n => { TabFullyQualifiedPath = n.GetStringValue(); } },
                { "tabId", n => { TabId = n.GetStringValue(); } },
                { "tabIdMetadata", n => { TabIdMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "tabOrder", n => { TabOrder = n.GetStringValue(); } },
                { "tabOrderMetadata", n => { TabOrderMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "underline", n => { Underline = n.GetStringValue(); } },
                { "underlineMetadata", n => { UnderlineMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "valueMetadata", n => { ValueMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "xPosition", n => { XPosition = n.GetStringValue(); } },
                { "xPositionMetadata", n => { XPositionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "yPosition", n => { YPosition = n.GetStringValue(); } },
                { "yPositionMetadata", n => { YPositionMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("anchorAllowWhiteSpaceInCharacters", AnchorAllowWhiteSpaceInCharacters);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorAllowWhiteSpaceInCharactersMetadata", AnchorAllowWhiteSpaceInCharactersMetadata);
            writer.WriteStringValue("anchorCaseSensitive", AnchorCaseSensitive);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorCaseSensitiveMetadata", AnchorCaseSensitiveMetadata);
            writer.WriteStringValue("anchorHorizontalAlignment", AnchorHorizontalAlignment);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorHorizontalAlignmentMetadata", AnchorHorizontalAlignmentMetadata);
            writer.WriteStringValue("anchorIgnoreIfNotPresent", AnchorIgnoreIfNotPresent);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorIgnoreIfNotPresentMetadata", AnchorIgnoreIfNotPresentMetadata);
            writer.WriteStringValue("anchorMatchWholeWord", AnchorMatchWholeWord);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorMatchWholeWordMetadata", AnchorMatchWholeWordMetadata);
            writer.WriteStringValue("anchorString", AnchorString);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorStringMetadata", AnchorStringMetadata);
            writer.WriteStringValue("anchorTabProcessorVersion", AnchorTabProcessorVersion);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorTabProcessorVersionMetadata", AnchorTabProcessorVersionMetadata);
            writer.WriteStringValue("anchorUnits", AnchorUnits);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorUnitsMetadata", AnchorUnitsMetadata);
            writer.WriteStringValue("anchorXOffset", AnchorXOffset);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorXOffsetMetadata", AnchorXOffsetMetadata);
            writer.WriteStringValue("anchorYOffset", AnchorYOffset);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("anchorYOffsetMetadata", AnchorYOffsetMetadata);
            writer.WriteStringValue("bold", Bold);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("boldMetadata", BoldMetadata);
            writer.WriteStringValue("caption", Caption);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("captionMetadata", CaptionMetadata);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ConnectedObjectDetails>("connectedObjectDetails", ConnectedObjectDetails);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ExtensionData>("extensionData", ExtensionData);
            writer.WriteStringValue("font", Font);
            writer.WriteStringValue("fontColor", FontColor);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("fontColorMetadata", FontColorMetadata);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("fontMetadata", FontMetadata);
            writer.WriteStringValue("fontSize", FontSize);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("fontSizeMetadata", FontSizeMetadata);
            writer.WriteStringValue("italic", Italic);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("italicMetadata", ItalicMetadata);
            writer.WriteStringValue("locked", Locked);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("lockedMetadata", LockedMetadata);
            writer.WriteStringValue("mergeFieldXml", MergeFieldXml);
            writer.WriteStringValue("pageNumber", PageNumber);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("pageNumberMetadata", PageNumberMetadata);
            writer.WriteStringValue("required", Required);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("requiredMetadata", RequiredMetadata);
            writer.WriteStringValue("selected", Selected);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("selectedMetadata", SelectedMetadata);
            writer.WriteStringValue("status", Status);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("statusMetadata", StatusMetadata);
            writer.WriteStringValue("tabFullyQualifiedPath", TabFullyQualifiedPath);
            writer.WriteStringValue("tabId", TabId);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("tabIdMetadata", TabIdMetadata);
            writer.WriteStringValue("tabOrder", TabOrder);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("tabOrderMetadata", TabOrderMetadata);
            writer.WriteStringValue("underline", Underline);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("underlineMetadata", UnderlineMetadata);
            writer.WriteStringValue("value", Value);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("valueMetadata", ValueMetadata);
            writer.WriteStringValue("xPosition", XPosition);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("xPositionMetadata", XPositionMetadata);
            writer.WriteStringValue("yPosition", YPosition);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("yPositionMetadata", YPositionMetadata);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
