// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// An Electronic or Standards Based Signature (digital signature) provider for the signer to use. [More information](/docs/esign-rest-api/esign101/concepts/standards-based-signatures/).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecipientSignatureProvider : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>By default, electronic seals apply on all documents in an envelope. If any of the documents has a `signHere` tab, then a visual representation of the electronic seal will show up in the final document. If not, the electronic seal will be visible in the metadata but not in the content of the document.To apply electronic seals on specific documents only, you must enable the  `sealDocumentsWithTabsOnly` parameter. In this case, Electronic Seal applies only on documents that have `signHere` tabs set for the Electronic Seal recipient. Other documents won&apos;t be sealed. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SealDocumentsWithTabsOnly { get; set; }
#nullable restore
#else
        public string SealDocumentsWithTabsOnly { get; set; }
#endif
        /// <summary>Indicates the name of the electronic seal to apply on documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SealName { get; set; }
#nullable restore
#else
        public string SealName { get; set; }
#endif
        /// <summary>The name of an Electronic or Standards Based Signature (digital signature) provider for the signer to use. For details, see [the current provider list](/docs/esign-rest-api/esign101/concepts/standards-based-signatures/). You can also retrieve the list by using the [AccountSignatureProviders: List](/docs/esign-rest-api/reference/accounts/accountsignatureproviders/list/) method.Example: `universalsignaturepen_default`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatureProviderName { get; set; }
#nullable restore
#else
        public string SignatureProviderName { get; set; }
#endif
        /// <summary>Metadata about a property.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.PropertyMetadata? SignatureProviderNameMetadata { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.PropertyMetadata SignatureProviderNameMetadata { get; set; }
#endif
        /// <summary>Option settings for the signature provider. Different providers require or use different options. [The current provider list and the options they require.](/docs/esign-rest-api/esign101/concepts/standards-based-signatures/)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.RecipientSignatureProviderOptions? SignatureProviderOptions { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.RecipientSignatureProviderOptions SignatureProviderOptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.RecipientSignatureProvider"/> and sets the default values.
        /// </summary>
        public RecipientSignatureProvider()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.RecipientSignatureProvider"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.RecipientSignatureProvider CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.RecipientSignatureProvider();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "sealDocumentsWithTabsOnly", n => { SealDocumentsWithTabsOnly = n.GetStringValue(); } },
                { "sealName", n => { SealName = n.GetStringValue(); } },
                { "signatureProviderName", n => { SignatureProviderName = n.GetStringValue(); } },
                { "signatureProviderNameMetadata", n => { SignatureProviderNameMetadata = n.GetObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>(global::DocuSignKiota.Client.Models.PropertyMetadata.CreateFromDiscriminatorValue); } },
                { "signatureProviderOptions", n => { SignatureProviderOptions = n.GetObjectValue<global::DocuSignKiota.Client.Models.RecipientSignatureProviderOptions>(global::DocuSignKiota.Client.Models.RecipientSignatureProviderOptions.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("sealDocumentsWithTabsOnly", SealDocumentsWithTabsOnly);
            writer.WriteStringValue("sealName", SealName);
            writer.WriteStringValue("signatureProviderName", SignatureProviderName);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.PropertyMetadata>("signatureProviderNameMetadata", SignatureProviderNameMetadata);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.RecipientSignatureProviderOptions>("signatureProviderOptions", SignatureProviderOptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
