// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Contains details about a signing group. Signing groups enable you to send an envelope to a predefined group of recipients and have any one member of the group sign your documents. When you send an envelope to a signing group, anyone in the group can open it and sign it with their own signature.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SigningGroup : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The UTC DateTime when the signing group was created. This property is read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Created { get; set; }
#nullable restore
#else
        public string Created { get; set; }
#endif
        /// <summary>The name of the user who created the signing group. This property is read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>The email address for the signing group. You can use a group email address to email all of the group members at the same time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupEmail { get; set; }
#nullable restore
#else
        public string GroupEmail { get; set; }
#endif
        /// <summary>The name of the group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupName { get; set; }
#nullable restore
#else
        public string GroupName { get; set; }
#endif
        /// <summary>The type of the group. The only valid value for this request is `sharedSigningGroup`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupType { get; set; }
#nullable restore
#else
        public string GroupType { get; set; }
#endif
        /// <summary>The UTC DateTime when the signing group was last modified. This property is read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Modified { get; set; }
#nullable restore
#else
        public string Modified { get; set; }
#endif
        /// <summary>The user ID (GUID) of the user who last modified this user record. This property is read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModifiedBy { get; set; }
#nullable restore
#else
        public string ModifiedBy { get; set; }
#endif
        /// <summary>The ID of the [signing group](https://support.docusign.com/s/document-item?bundleId=gav1643676262430&amp;topicId=zgn1578456447934.html).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SigningGroupId { get; set; }
#nullable restore
#else
        public string SigningGroupId { get; set; }
#endif
        /// <summary>User management information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DocuSignKiota.Client.Models.SigningGroupUser>? Users { get; set; }
#nullable restore
#else
        public List<global::DocuSignKiota.Client.Models.SigningGroupUser> Users { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.SigningGroup"/> and sets the default values.
        /// </summary>
        public SigningGroup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.SigningGroup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.SigningGroup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.SigningGroup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "groupEmail", n => { GroupEmail = n.GetStringValue(); } },
                { "groupName", n => { GroupName = n.GetStringValue(); } },
                { "groupType", n => { GroupType = n.GetStringValue(); } },
                { "modified", n => { Modified = n.GetStringValue(); } },
                { "modifiedBy", n => { ModifiedBy = n.GetStringValue(); } },
                { "signingGroupId", n => { SigningGroupId = n.GetStringValue(); } },
                { "users", n => { Users = n.GetCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SigningGroupUser>(global::DocuSignKiota.Client.Models.SigningGroupUser.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("created", Created);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("groupEmail", GroupEmail);
            writer.WriteStringValue("groupName", GroupName);
            writer.WriteStringValue("groupType", GroupType);
            writer.WriteStringValue("modified", Modified);
            writer.WriteStringValue("modifiedBy", ModifiedBy);
            writer.WriteStringValue("signingGroupId", SigningGroupId);
            writer.WriteCollectionOfObjectValues<global::DocuSignKiota.Client.Models.SigningGroupUser>("users", Users);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
