// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Stamp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The UTC date and time when the user adopted the signature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdoptedDateTime { get; set; }
#nullable restore
#else
        public string AdoptedDateTime { get; set; }
#endif
        /// <summary>The UTC DateTime when the item was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedDateTime { get; set; }
#nullable restore
#else
        public string CreatedDateTime { get; set; }
#endif
        /// <summary>The customField property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomField { get; set; }
#nullable restore
#else
        public string CustomField { get; set; }
#endif
        /// <summary>Specifies the area in which a date stamp is placed. This parameter uses pixel positioning to draw a rectangle at the center of the stamp area. The stamp is superimposed on top of this central area.This property contains the following information about the central rectangle:- `DateAreaX`: The X axis position of the top-left corner.- `DateAreaY`: The Y axis position of the top-left corner.- `DateAreaWidth`: The width of the rectangle.- `DateAreaHeight`: The height of the rectangle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.DateStampProperties? DateStampProperties { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.DateStampProperties DateStampProperties { get; set; }
#endif
        /// <summary>When **true,** users may not resize the stamp.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisallowUserResizeStamp { get; set; }
#nullable restore
#else
        public string DisallowUserResizeStamp { get; set; }
#endif
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>Optionally specify an external identifier for the user&apos;s signature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalID { get; set; }
#nullable restore
#else
        public string ExternalID { get; set; }
#endif
        /// <summary>The imageBase64 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageBase64 { get; set; }
#nullable restore
#else
        public string ImageBase64 { get; set; }
#endif
        /// <summary>Specificies the type of image. Valid values:- `stamp_image`- `signature_image`- `initials_image`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageType { get; set; }
#nullable restore
#else
        public string ImageType { get; set; }
#endif
        /// <summary>The date and time that the item was last modified.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastModifiedDateTime { get; set; }
#nullable restore
#else
        public string LastModifiedDateTime { get; set; }
#endif
        /// <summary>The phonetic spelling of the `signatureName`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneticName { get; set; }
#nullable restore
#else
        public string PhoneticName { get; set; }
#endif
        /// <summary>Specifies the user&apos;s signature name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatureName { get; set; }
#nullable restore
#else
        public string SignatureName { get; set; }
#endif
        /// <summary>The format of a stamp. Valid values are:- `NameHanko`: The stamp represents only the signer&apos;s name.- `NameDateHanko`: The stamp represents the signer&apos;s name and the date. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StampFormat { get; set; }
#nullable restore
#else
        public string StampFormat { get; set; }
#endif
        /// <summary>The URI for retrieving the image of the user&apos;s stamp.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StampImageUri { get; set; }
#nullable restore
#else
        public string StampImageUri { get; set; }
#endif
        /// <summary>The physical height of the stamp image (in millimeters) that the stamp vendor recommends for displaying the image in PDF documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StampSizeMM { get; set; }
#nullable restore
#else
        public string StampSizeMM { get; set; }
#endif
        /// <summary>Indicates the envelope status. Valid values are:* sent - The envelope is sent to the recipients. * created - The envelope is saved as a draft and can be modified and sent later.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.Stamp"/> and sets the default values.
        /// </summary>
        public Stamp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.Stamp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.Stamp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.Stamp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adoptedDateTime", n => { AdoptedDateTime = n.GetStringValue(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetStringValue(); } },
                { "customField", n => { CustomField = n.GetStringValue(); } },
                { "dateStampProperties", n => { DateStampProperties = n.GetObjectValue<global::DocuSignKiota.Client.Models.DateStampProperties>(global::DocuSignKiota.Client.Models.DateStampProperties.CreateFromDiscriminatorValue); } },
                { "disallowUserResizeStamp", n => { DisallowUserResizeStamp = n.GetStringValue(); } },
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "externalID", n => { ExternalID = n.GetStringValue(); } },
                { "imageBase64", n => { ImageBase64 = n.GetStringValue(); } },
                { "imageType", n => { ImageType = n.GetStringValue(); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetStringValue(); } },
                { "phoneticName", n => { PhoneticName = n.GetStringValue(); } },
                { "signatureName", n => { SignatureName = n.GetStringValue(); } },
                { "stampFormat", n => { StampFormat = n.GetStringValue(); } },
                { "stampImageUri", n => { StampImageUri = n.GetStringValue(); } },
                { "stampSizeMM", n => { StampSizeMM = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("adoptedDateTime", AdoptedDateTime);
            writer.WriteStringValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("customField", CustomField);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.DateStampProperties>("dateStampProperties", DateStampProperties);
            writer.WriteStringValue("disallowUserResizeStamp", DisallowUserResizeStamp);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("externalID", ExternalID);
            writer.WriteStringValue("imageBase64", ImageBase64);
            writer.WriteStringValue("imageType", ImageType);
            writer.WriteStringValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteStringValue("phoneticName", PhoneticName);
            writer.WriteStringValue("signatureName", SignatureName);
            writer.WriteStringValue("stampFormat", StampFormat);
            writer.WriteStringValue("stampImageUri", StampImageUri);
            writer.WriteStringValue("stampSizeMM", StampSizeMM);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
