// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DocuSignKiota.Client.Models
{
    /// <summary>
    /// Information about a shared item.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserSharedItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>This object describes errors that occur. It is only valid for responses and ignored in requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.ErrorDetails? ErrorDetails { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.ErrorDetails ErrorDetails { get; set; }
#endif
        /// <summary>How the item is shared. One of:- `not_shared`- `shared_to`- `shared_from`- `shared_to_and_from`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Shared { get; set; }
#nullable restore
#else
        public string Shared { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DocuSignKiota.Client.Models.UserInfo? User { get; set; }
#nullable restore
#else
        public global::DocuSignKiota.Client.Models.UserInfo User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.Models.UserSharedItem"/> and sets the default values.
        /// </summary>
        public UserSharedItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DocuSignKiota.Client.Models.UserSharedItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DocuSignKiota.Client.Models.UserSharedItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::DocuSignKiota.Client.Models.UserSharedItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorDetails", n => { ErrorDetails = n.GetObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>(global::DocuSignKiota.Client.Models.ErrorDetails.CreateFromDiscriminatorValue); } },
                { "shared", n => { Shared = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::DocuSignKiota.Client.Models.UserInfo>(global::DocuSignKiota.Client.Models.UserInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.ErrorDetails>("errorDetails", ErrorDetails);
            writer.WriteStringValue("shared", Shared);
            writer.WriteObjectValue<global::DocuSignKiota.Client.Models.UserInfo>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
