// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V2.Core.Accounts.Item
{
    /// <summary>
    /// Default responsibilities held by either Stripe or the platform.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account_PostRequestBody_defaults_responsibilities : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A value indicating the party responsible for collecting fees from this account.</summary>
        public global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_fees_collector? FeesCollector { get; set; }
        /// <summary>A value indicating who is responsible for losses when this Account can’t pay back negative balances from payments.</summary>
        public global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_losses_collector? LossesCollector { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities"/> and sets the default values.
        /// </summary>
        public Account_PostRequestBody_defaults_responsibilities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "fees_collector", n => { FeesCollector = n.GetEnumValue<global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_fees_collector>(); } },
                { "losses_collector", n => { LossesCollector = n.GetEnumValue<global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_losses_collector>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_fees_collector>("fees_collector", FeesCollector);
            writer.WriteEnumValue<global::StripeKiota.Client.V2.Core.Accounts.Item.Account_PostRequestBody_defaults_responsibilities_losses_collector>("losses_collector", LossesCollector);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
