// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.V2.Core.Accounts.Item
{
    /// <summary>Indicates whether displayed line item prices and amounts on invoice PDFs include inclusive tax amounts. Must be either `include_inclusive_tax` or `exclude_tax`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Account_PostRequestBody_configuration_customer_billing_invoice_rendering_amount_tax_display
    {
        [EnumMember(Value = "exclude_tax")]
        #pragma warning disable CS1591
        Exclude_tax,
        #pragma warning restore CS1591
        [EnumMember(Value = "include_inclusive_tax")]
        #pragma warning disable CS1591
        Include_inclusive_tax,
        #pragma warning restore CS1591
    }
}
