// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.V2.Core.Accounts.Item
{
    /// <summary>A value indicating the Stripe dashboard this Account has access to. This will depend on which configurations are enabled for this account.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Account_PostRequestBody_dashboard
    {
        [EnumMember(Value = "express")]
        #pragma warning disable CS1591
        Express,
        #pragma warning restore CS1591
        [EnumMember(Value = "full")]
        #pragma warning disable CS1591
        Full,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
