// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V2.Core.Account_tokens
{
    /// <summary>
    /// This hash is used to attest that the directors information provided to Stripe is both current and correct; IP, date, and User Agent are expanded by Stripe.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account_tokensPostRequestBody_identity_attestations_directorship_declaration : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A boolean indicating if the directors information has been attested.</summary>
        public bool? Attested { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V2.Core.Account_tokens.Account_tokensPostRequestBody_identity_attestations_directorship_declaration"/> and sets the default values.
        /// </summary>
        public Account_tokensPostRequestBody_identity_attestations_directorship_declaration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V2.Core.Account_tokens.Account_tokensPostRequestBody_identity_attestations_directorship_declaration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.V2.Core.Account_tokens.Account_tokensPostRequestBody_identity_attestations_directorship_declaration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V2.Core.Account_tokens.Account_tokensPostRequestBody_identity_attestations_directorship_declaration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attested", n => { Attested = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("attested", Attested);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
