// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.V2.Core.Account_tokens
{
    /// <summary>The ID number type of an individual.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Account_tokensPostRequestBody_identity_individual_id_numbers_type
    {
        [EnumMember(Value = "ae_eid")]
        #pragma warning disable CS1591
        Ae_eid,
        #pragma warning restore CS1591
        [EnumMember(Value = "ao_nif")]
        #pragma warning disable CS1591
        Ao_nif,
        #pragma warning restore CS1591
        [EnumMember(Value = "ar_cuil")]
        #pragma warning disable CS1591
        Ar_cuil,
        #pragma warning restore CS1591
        [EnumMember(Value = "ar_dni")]
        #pragma warning disable CS1591
        Ar_dni,
        #pragma warning restore CS1591
        [EnumMember(Value = "at_stn")]
        #pragma warning disable CS1591
        At_stn,
        #pragma warning restore CS1591
        [EnumMember(Value = "az_tin")]
        #pragma warning disable CS1591
        Az_tin,
        #pragma warning restore CS1591
        [EnumMember(Value = "bd_brc")]
        #pragma warning disable CS1591
        Bd_brc,
        #pragma warning restore CS1591
        [EnumMember(Value = "bd_etin")]
        #pragma warning disable CS1591
        Bd_etin,
        #pragma warning restore CS1591
        [EnumMember(Value = "bd_nid")]
        #pragma warning disable CS1591
        Bd_nid,
        #pragma warning restore CS1591
        [EnumMember(Value = "be_nrn")]
        #pragma warning disable CS1591
        Be_nrn,
        #pragma warning restore CS1591
        [EnumMember(Value = "bg_ucn")]
        #pragma warning disable CS1591
        Bg_ucn,
        #pragma warning restore CS1591
        [EnumMember(Value = "bn_nric")]
        #pragma warning disable CS1591
        Bn_nric,
        #pragma warning restore CS1591
        [EnumMember(Value = "br_cpf")]
        #pragma warning disable CS1591
        Br_cpf,
        #pragma warning restore CS1591
        [EnumMember(Value = "ca_sin")]
        #pragma warning disable CS1591
        Ca_sin,
        #pragma warning restore CS1591
        [EnumMember(Value = "ch_oasi")]
        #pragma warning disable CS1591
        Ch_oasi,
        #pragma warning restore CS1591
        [EnumMember(Value = "cl_rut")]
        #pragma warning disable CS1591
        Cl_rut,
        #pragma warning restore CS1591
        [EnumMember(Value = "cn_pp")]
        #pragma warning disable CS1591
        Cn_pp,
        #pragma warning restore CS1591
        [EnumMember(Value = "co_nuip")]
        #pragma warning disable CS1591
        Co_nuip,
        #pragma warning restore CS1591
        [EnumMember(Value = "cr_ci")]
        #pragma warning disable CS1591
        Cr_ci,
        #pragma warning restore CS1591
        [EnumMember(Value = "cr_cpf")]
        #pragma warning disable CS1591
        Cr_cpf,
        #pragma warning restore CS1591
        [EnumMember(Value = "cr_dimex")]
        #pragma warning disable CS1591
        Cr_dimex,
        #pragma warning restore CS1591
        [EnumMember(Value = "cr_nite")]
        #pragma warning disable CS1591
        Cr_nite,
        #pragma warning restore CS1591
        [EnumMember(Value = "cy_tic")]
        #pragma warning disable CS1591
        Cy_tic,
        #pragma warning restore CS1591
        [EnumMember(Value = "cz_rc")]
        #pragma warning disable CS1591
        Cz_rc,
        #pragma warning restore CS1591
        [EnumMember(Value = "de_stn")]
        #pragma warning disable CS1591
        De_stn,
        #pragma warning restore CS1591
        [EnumMember(Value = "dk_cpr")]
        #pragma warning disable CS1591
        Dk_cpr,
        #pragma warning restore CS1591
        [EnumMember(Value = "do_cie")]
        #pragma warning disable CS1591
        Do_cie,
        #pragma warning restore CS1591
        [EnumMember(Value = "do_rcn")]
        #pragma warning disable CS1591
        Do_rcn,
        #pragma warning restore CS1591
        [EnumMember(Value = "ec_ci")]
        #pragma warning disable CS1591
        Ec_ci,
        #pragma warning restore CS1591
        [EnumMember(Value = "ee_ik")]
        #pragma warning disable CS1591
        Ee_ik,
        #pragma warning restore CS1591
        [EnumMember(Value = "es_nif")]
        #pragma warning disable CS1591
        Es_nif,
        #pragma warning restore CS1591
        [EnumMember(Value = "fi_hetu")]
        #pragma warning disable CS1591
        Fi_hetu,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr_nir")]
        #pragma warning disable CS1591
        Fr_nir,
        #pragma warning restore CS1591
        [EnumMember(Value = "gb_nino")]
        #pragma warning disable CS1591
        Gb_nino,
        #pragma warning restore CS1591
        [EnumMember(Value = "gr_afm")]
        #pragma warning disable CS1591
        Gr_afm,
        #pragma warning restore CS1591
        [EnumMember(Value = "gt_nit")]
        #pragma warning disable CS1591
        Gt_nit,
        #pragma warning restore CS1591
        [EnumMember(Value = "hk_id")]
        #pragma warning disable CS1591
        Hk_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "hr_oib")]
        #pragma warning disable CS1591
        Hr_oib,
        #pragma warning restore CS1591
        [EnumMember(Value = "hu_ad")]
        #pragma warning disable CS1591
        Hu_ad,
        #pragma warning restore CS1591
        [EnumMember(Value = "id_nik")]
        #pragma warning disable CS1591
        Id_nik,
        #pragma warning restore CS1591
        [EnumMember(Value = "ie_ppsn")]
        #pragma warning disable CS1591
        Ie_ppsn,
        #pragma warning restore CS1591
        [EnumMember(Value = "is_kt")]
        #pragma warning disable CS1591
        Is_kt,
        #pragma warning restore CS1591
        [EnumMember(Value = "it_cf")]
        #pragma warning disable CS1591
        It_cf,
        #pragma warning restore CS1591
        [EnumMember(Value = "jp_inc")]
        #pragma warning disable CS1591
        Jp_inc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ke_pin")]
        #pragma warning disable CS1591
        Ke_pin,
        #pragma warning restore CS1591
        [EnumMember(Value = "kz_iin")]
        #pragma warning disable CS1591
        Kz_iin,
        #pragma warning restore CS1591
        [EnumMember(Value = "li_peid")]
        #pragma warning disable CS1591
        Li_peid,
        #pragma warning restore CS1591
        [EnumMember(Value = "lt_ak")]
        #pragma warning disable CS1591
        Lt_ak,
        #pragma warning restore CS1591
        [EnumMember(Value = "lu_nif")]
        #pragma warning disable CS1591
        Lu_nif,
        #pragma warning restore CS1591
        [EnumMember(Value = "lv_pk")]
        #pragma warning disable CS1591
        Lv_pk,
        #pragma warning restore CS1591
        [EnumMember(Value = "mx_rfc")]
        #pragma warning disable CS1591
        Mx_rfc,
        #pragma warning restore CS1591
        [EnumMember(Value = "my_nric")]
        #pragma warning disable CS1591
        My_nric,
        #pragma warning restore CS1591
        [EnumMember(Value = "mz_nuit")]
        #pragma warning disable CS1591
        Mz_nuit,
        #pragma warning restore CS1591
        [EnumMember(Value = "ng_nin")]
        #pragma warning disable CS1591
        Ng_nin,
        #pragma warning restore CS1591
        [EnumMember(Value = "nl_bsn")]
        #pragma warning disable CS1591
        Nl_bsn,
        #pragma warning restore CS1591
        [EnumMember(Value = "no_nin")]
        #pragma warning disable CS1591
        No_nin,
        #pragma warning restore CS1591
        [EnumMember(Value = "nz_ird")]
        #pragma warning disable CS1591
        Nz_ird,
        #pragma warning restore CS1591
        [EnumMember(Value = "pe_dni")]
        #pragma warning disable CS1591
        Pe_dni,
        #pragma warning restore CS1591
        [EnumMember(Value = "pk_cnic")]
        #pragma warning disable CS1591
        Pk_cnic,
        #pragma warning restore CS1591
        [EnumMember(Value = "pk_snic")]
        #pragma warning disable CS1591
        Pk_snic,
        #pragma warning restore CS1591
        [EnumMember(Value = "pl_pesel")]
        #pragma warning disable CS1591
        Pl_pesel,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt_nif")]
        #pragma warning disable CS1591
        Pt_nif,
        #pragma warning restore CS1591
        [EnumMember(Value = "ro_cnp")]
        #pragma warning disable CS1591
        Ro_cnp,
        #pragma warning restore CS1591
        [EnumMember(Value = "sa_tin")]
        #pragma warning disable CS1591
        Sa_tin,
        #pragma warning restore CS1591
        [EnumMember(Value = "se_pin")]
        #pragma warning disable CS1591
        Se_pin,
        #pragma warning restore CS1591
        [EnumMember(Value = "sg_fin")]
        #pragma warning disable CS1591
        Sg_fin,
        #pragma warning restore CS1591
        [EnumMember(Value = "sg_nric")]
        #pragma warning disable CS1591
        Sg_nric,
        #pragma warning restore CS1591
        [EnumMember(Value = "sk_dic")]
        #pragma warning disable CS1591
        Sk_dic,
        #pragma warning restore CS1591
        [EnumMember(Value = "th_lc")]
        #pragma warning disable CS1591
        Th_lc,
        #pragma warning restore CS1591
        [EnumMember(Value = "th_pin")]
        #pragma warning disable CS1591
        Th_pin,
        #pragma warning restore CS1591
        [EnumMember(Value = "tr_tin")]
        #pragma warning disable CS1591
        Tr_tin,
        #pragma warning restore CS1591
        [EnumMember(Value = "us_itin")]
        #pragma warning disable CS1591
        Us_itin,
        #pragma warning restore CS1591
        [EnumMember(Value = "us_itin_last_4")]
        #pragma warning disable CS1591
        Us_itin_last_4,
        #pragma warning restore CS1591
        [EnumMember(Value = "us_ssn")]
        #pragma warning disable CS1591
        Us_ssn,
        #pragma warning restore CS1591
        [EnumMember(Value = "us_ssn_last_4")]
        #pragma warning disable CS1591
        Us_ssn_last_4,
        #pragma warning restore CS1591
        [EnumMember(Value = "uy_dni")]
        #pragma warning disable CS1591
        Uy_dni,
        #pragma warning restore CS1591
        [EnumMember(Value = "za_id")]
        #pragma warning disable CS1591
        Za_id,
        #pragma warning restore CS1591
    }
}
