// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.Models.V2.Core
{
    /// <summary>
    /// Hash containing usage options.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account_link_use_case : IAdditionalDataHolder, IParsable
    {
        /// <summary>Hash containing configuration options for an Account Link object that onboards a new account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_onboarding? AccountOnboarding { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_onboarding AccountOnboarding { get; set; }
#endif
        /// <summary>Hash containing configuration options for an Account Link that updates an existing account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_update? AccountUpdate { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_update AccountUpdate { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Open Enum. The type of Account Link the user is requesting.</summary>
        public global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.Models.V2.Core.Account_link_use_case"/> and sets the default values.
        /// </summary>
        public Account_link_use_case()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.Models.V2.Core.Account_link_use_case"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.Models.V2.Core.Account_link_use_case CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.Models.V2.Core.Account_link_use_case();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account_onboarding", n => { AccountOnboarding = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_onboarding>(global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_onboarding.CreateFromDiscriminatorValue); } },
                { "account_update", n => { AccountUpdate = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_update>(global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_update.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_onboarding>("account_onboarding", AccountOnboarding);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_account_update>("account_update", AccountUpdate);
            writer.WriteEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_link_use_case_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
