// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.Models.V2.Core
{
    /// <summary>Specifies whether the platform collects future_requirements in addition to requirements in Connect Onboarding. The default value is `omit`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Account_link_use_case_account_onboarding_collection_options_future_requirements
    {
        [EnumMember(Value = "include")]
        #pragma warning disable CS1591
        Include,
        #pragma warning restore CS1591
        [EnumMember(Value = "omit")]
        #pragma warning disable CS1591
        Omit,
        #pragma warning restore CS1591
    }
}
