// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.Models.V2.Core
{
    /// <summary>
    /// An Account v2 object represents a company, individual, or other entity that interacts with a platform on Stripe. It contains both identifying information and properties that control its behavior and functionality. An Account can have one or more configurations that enable sets of related features, such as allowing it to act as a merchant or customer.The Accounts v2 API supports both the Global Payouts preview feature and the Connect-Billing integration preview feature. However, a particular Account can only access one of them.The Connect-Billing integration preview feature allows an Account v2 to pay subscription fees to a platform. An Account v1 required a separate Customer object to pay subscription fees.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Account : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The configurations that have been applied to this account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::StripeKiota.Client.Models.V2.Core.Account_applied_configurations?>? AppliedConfigurations { get; set; }
#nullable restore
#else
        public List<global::StripeKiota.Client.Models.V2.Core.Account_applied_configurations?> AppliedConfigurations { get; set; }
#endif
        /// <summary>Indicates whether the account has been closed.</summary>
        public bool? Closed { get; set; }
        /// <summary>An Account represents a company, individual, or other entity that a user interacts with. Accounts store identity information and one or more configurations that enable product-specific capabilities. You can assign configurations at creation or add them later.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_configuration? Configuration { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_configuration Configuration { get; set; }
#endif
        /// <summary>The default contact email address for the Account. Required when configuring the account as a merchant or recipient.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactEmail { get; set; }
#nullable restore
#else
        public string ContactEmail { get; set; }
#endif
        /// <summary>The default contact phone for the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactPhone { get; set; }
#nullable restore
#else
        public string ContactPhone { get; set; }
#endif
        /// <summary>Time at which the object was created. Represented as a RFC 3339 date &amp; time UTC value in millisecond precision, for example: 2022-09-18T13:22:18.123Z.</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>A value indicating the Stripe dashboard this Account has access to. This will depend on which configurations are enabled for this account.</summary>
        public global::StripeKiota.Client.Models.V2.Core.Account_dashboard? Dashboard { get; set; }
        /// <summary>Default values for settings shared across Account configurations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_defaults? Defaults { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_defaults Defaults { get; set; }
#endif
        /// <summary>A descriptive name for the Account. This name will be surfaced in the Stripe Dashboard and on any invoices sent to the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Information about the future requirements for the Account that will eventually come into effect, including what information needs to be collected, and by when.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_future_requirements? FutureRequirements { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_future_requirements FutureRequirements { get; set; }
#endif
        /// <summary>Unique identifier for the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Information about the company, individual, and business represented by the Account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_identity? Identity { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_identity Identity { get; set; }
#endif
        /// <summary>Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.</summary>
        public bool? Livemode { get; set; }
        /// <summary>Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_metadata Metadata { get; set; }
#endif
        /// <summary>String representing the object&apos;s type. Objects of the same type share the same value of the object field.</summary>
        public global::StripeKiota.Client.Models.V2.Core.Account_object? Object { get; set; }
        /// <summary>Information about the active requirements for the Account, including what information needs to be collected, and by when.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Core.Account_requirements? Requirements { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Core.Account_requirements Requirements { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.Models.V2.Core.Account"/> and sets the default values.
        /// </summary>
        public Account()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.Models.V2.Core.Account"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.Models.V2.Core.Account CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.Models.V2.Core.Account();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "applied_configurations", n => { AppliedConfigurations = n.GetCollectionOfEnumValues<global::StripeKiota.Client.Models.V2.Core.Account_applied_configurations>()?.AsList(); } },
                { "closed", n => { Closed = n.GetBoolValue(); } },
                { "configuration", n => { Configuration = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_configuration>(global::StripeKiota.Client.Models.V2.Core.Account_configuration.CreateFromDiscriminatorValue); } },
                { "contact_email", n => { ContactEmail = n.GetStringValue(); } },
                { "contact_phone", n => { ContactPhone = n.GetStringValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "dashboard", n => { Dashboard = n.GetEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_dashboard>(); } },
                { "defaults", n => { Defaults = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_defaults>(global::StripeKiota.Client.Models.V2.Core.Account_defaults.CreateFromDiscriminatorValue); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "future_requirements", n => { FutureRequirements = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_future_requirements>(global::StripeKiota.Client.Models.V2.Core.Account_future_requirements.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "identity", n => { Identity = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_identity>(global::StripeKiota.Client.Models.V2.Core.Account_identity.CreateFromDiscriminatorValue); } },
                { "livemode", n => { Livemode = n.GetBoolValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_metadata>(global::StripeKiota.Client.Models.V2.Core.Account_metadata.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_object>(); } },
                { "requirements", n => { Requirements = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_requirements>(global::StripeKiota.Client.Models.V2.Core.Account_requirements.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfEnumValues<global::StripeKiota.Client.Models.V2.Core.Account_applied_configurations>("applied_configurations", AppliedConfigurations);
            writer.WriteBoolValue("closed", Closed);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_configuration>("configuration", Configuration);
            writer.WriteStringValue("contact_email", ContactEmail);
            writer.WriteStringValue("contact_phone", ContactPhone);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_dashboard>("dashboard", Dashboard);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_defaults>("defaults", Defaults);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_future_requirements>("future_requirements", FutureRequirements);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_identity>("identity", Identity);
            writer.WriteBoolValue("livemode", Livemode);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_metadata>("metadata", Metadata);
            writer.WriteEnumValue<global::StripeKiota.Client.Models.V2.Core.Account_object>("object", Object);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Core.Account_requirements>("requirements", Requirements);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
