// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.Models.V2.Billing
{
    /// <summary>
    /// A Meter Event is a usage record that captures billable activity for usage-based billing. Meter Events contain an event name, timestamp, and payload with customer mapping and usage value, enabling accurate usage tracking and billing.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Meter_event : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation time of this meter event.</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The name of the meter event. Corresponds with the `event_name` field on a meter.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventName { get; set; }
#nullable restore
#else
        public string EventName { get; set; }
#endif
        /// <summary>A unique identifier for the event. If not provided, one will be generated. We recommend using a globally unique identifier for this. We’ll enforce uniqueness within a rolling 24 hour period.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Identifier { get; set; }
#nullable restore
#else
        public string Identifier { get; set; }
#endif
        /// <summary>Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.</summary>
        public bool? Livemode { get; set; }
        /// <summary>String representing the object&apos;s type. Objects of the same type share the same value of the object field.</summary>
        public global::StripeKiota.Client.Models.V2.Billing.Meter_event_object? Object { get; set; }
        /// <summary>The payload of the event. This must contain the fields corresponding to a meter’s`customer_mapping.event_payload_key` (default is `stripe_customer_id`) and`value_settings.event_payload_key` (default is `value`). Read more aboutthe [payload](https://docs.stripe.com/billing/subscriptions/usage-based/recording-usage#payload-key-overrides)..</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.Models.V2.Billing.Meter_event_payload? Payload { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.Models.V2.Billing.Meter_event_payload Payload { get; set; }
#endif
        /// <summary>The time of the event. Must be within the past 35 calendar days or up to5 minutes in the future. Defaults to current timestamp if not specified.</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.Models.V2.Billing.Meter_event"/> and sets the default values.
        /// </summary>
        public Meter_event()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.Models.V2.Billing.Meter_event"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.Models.V2.Billing.Meter_event CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.Models.V2.Billing.Meter_event();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "event_name", n => { EventName = n.GetStringValue(); } },
                { "identifier", n => { Identifier = n.GetStringValue(); } },
                { "livemode", n => { Livemode = n.GetBoolValue(); } },
                { "object", n => { Object = n.GetEnumValue<global::StripeKiota.Client.Models.V2.Billing.Meter_event_object>(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::StripeKiota.Client.Models.V2.Billing.Meter_event_payload>(global::StripeKiota.Client.Models.V2.Billing.Meter_event_payload.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteStringValue("event_name", EventName);
            writer.WriteStringValue("identifier", Identifier);
            writer.WriteBoolValue("livemode", Livemode);
            writer.WriteEnumValue<global::StripeKiota.Client.Models.V2.Billing.Meter_event_object>("object", Object);
            writer.WriteObjectValue<global::StripeKiota.Client.Models.V2.Billing.Meter_event_payload>("payload", Payload);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
