// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.V2.Commerce.Product_catalog.Imports
{
    /// <summary>The type of catalog data to import.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ImportsPostRequestBody_feed_type
    {
        [EnumMember(Value = "inventory")]
        #pragma warning disable CS1591
        Inventory,
        #pragma warning restore CS1591
        [EnumMember(Value = "pricing")]
        #pragma warning disable CS1591
        Pricing,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
    }
}
