// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V2.Core.Event_destinations
{
    [Obsolete("This class is obsolete. Use Event_destinationsGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Event_destinationsResponse : global::StripeKiota.Client.V2.Core.Event_destinations.Event_destinationsGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V2.Core.Event_destinations.Event_destinationsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::StripeKiota.Client.V2.Core.Event_destinations.Event_destinationsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V2.Core.Event_destinations.Event_destinationsResponse();
        }
    }
}
#pragma warning restore CS0618
