// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace StripeKiota.Client.V2.Core.Event_destinations
{
    /// <summary>Payload type of events being subscribed to.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Event_destinationsPostRequestBody_event_payload
    {
        [EnumMember(Value = "snapshot")]
        #pragma warning disable CS1591
        Snapshot,
        #pragma warning restore CS1591
        [EnumMember(Value = "thin")]
        #pragma warning disable CS1591
        Thin,
        #pragma warning restore CS1591
    }
}
