// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace GitHubKiota.Client.Installation.Repositories
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RepositoriesGetResponse_repositories : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The custom properties that were defined for the repository. The keys are the custom property names, and the values are the corresponding custom property values. Present for org repos only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories_custom_properties? CustomProperties { get; set; }
#nullable restore
#else
        public global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories_custom_properties CustomProperties { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories"/> and sets the default values.
        /// </summary>
        public RepositoriesGetResponse_repositories()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "custom_properties", n => { CustomProperties = n.GetObjectValue<global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories_custom_properties>(global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories_custom_properties.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::GitHubKiota.Client.Installation.Repositories.RepositoriesGetResponse_repositories_custom_properties>("custom_properties", CustomProperties);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
