// <auto-generated/>
#pragma warning disable CS0618
using DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos
{
    /// <summary>
    /// Builds and executes requests for operations under \v2.1\accounts\{accountId}\brands\{brandId}\logos
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LogosRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DocuSignKiota.Client.v21.accounts.item.brands.item.logos.item collection</summary>
        /// <param name="position">The type of logo. Valid values are:- `primary` - `secondary` - `email`</param>
        /// <returns>A <see cref="global::DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.Item.WithLogoTypeItemRequestBuilder"/></returns>
        public global::DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.Item.WithLogoTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("logoType", position);
                return new global::DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.Item.WithLogoTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.LogosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogosRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2.1/accounts/{accountId}/brands/{brandId}/logos", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DocuSignKiota.Client.V21.Accounts.Item.Brands.Item.Logos.LogosRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LogosRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2.1/accounts/{accountId}/brands/{brandId}/logos", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
