// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V2.Core.Accounts
{
    /// <summary>
    /// Support for Konbini payments.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsPostRequestBody_configuration_merchant_konbini_payments_support : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Support email address for Konbini payments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Support hours for Konbini payments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support_hours? Hours { get; set; }
#nullable restore
#else
        public global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support_hours Hours { get; set; }
#endif
        /// <summary>Support phone number for Konbini payments.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support"/> and sets the default values.
        /// </summary>
        public AccountsPostRequestBody_configuration_merchant_konbini_payments_support()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "email", n => { Email = n.GetStringValue(); } },
                { "hours", n => { Hours = n.GetObjectValue<global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support_hours>(global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support_hours.CreateFromDiscriminatorValue); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_configuration_merchant_konbini_payments_support_hours>("hours", Hours);
            writer.WriteStringValue("phone", Phone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
