// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V2.Core.Accounts
{
    /// <summary>
    /// The [file upload](https://docs.stripe.com/api/persons/update#create_file) tokens referring to each side of the document.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A [file upload](https://docs.stripe.com/api/persons/update#create_file) token representing the back of the verification document. The purpose of the uploaded file should be &apos;identity_document&apos;. The uploaded file needs to be a color image (smaller than 8,000px by 8,000px), in JPG, PNG, or PDF format, and less than 10 MB in size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Back { get; set; }
#nullable restore
#else
        public string Back { get; set; }
#endif
        /// <summary>A [file upload](https://docs.stripe.com/api/persons/update#create_file) token representing the front of the verification document. The purpose of the uploaded file should be &apos;identity_document&apos;. The uploaded file needs to be a color image (smaller than 8,000px by 8,000px), in JPG, PNG, or PDF format, and less than 10 MB in size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Front { get; set; }
#nullable restore
#else
        public string Front { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back"/> and sets the default values.
        /// </summary>
        public AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V2.Core.Accounts.AccountsPostRequestBody_identity_business_details_documents_primary_verification_front_back();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "back", n => { Back = n.GetStringValue(); } },
                { "front", n => { Front = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("back", Back);
            writer.WriteStringValue("front", Front);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
