// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StripeKiota.Client.V1.Financial_connections.Accounts.Item.Owners
{
    [Obsolete("This class is obsolete. Use OwnersGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OwnersResponse : global::StripeKiota.Client.V1.Financial_connections.Accounts.Item.Owners.OwnersGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V1.Financial_connections.Accounts.Item.Owners.OwnersResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::StripeKiota.Client.V1.Financial_connections.Accounts.Item.Owners.OwnersResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::StripeKiota.Client.V1.Financial_connections.Accounts.Item.Owners.OwnersResponse();
        }
    }
}
#pragma warning restore CS0618
