// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using StripeKiota.Client.Models.Treasury;
using StripeKiota.Client.Models;
using StripeKiota.Client.V1.Treasury.Outbound_transfers.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace StripeKiota.Client.V1.Treasury.Outbound_transfers
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\treasury\outbound_transfers
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Outbound_transfersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the StripeKiota.Client.v1.treasury.outbound_transfers.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Item.WithOutbound_transferItemRequestBuilder"/></returns>
        public global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Item.WithOutbound_transferItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("outbound_transfer", position);
                return new global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Item.WithOutbound_transferItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Outbound_transfersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/treasury/outbound_transfers?financial_account={financial_account}{&ending_before*,expand*,limit*,starting_after*,status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Outbound_transfersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/treasury/outbound_transfers?financial_account={financial_account}{&ending_before*,expand*,limit*,starting_after*,status*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;p&gt;Returns a list of OutboundTransfers sent from the specified FinancialAccount.&lt;/p&gt;
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::StripeKiota.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetResponse?> GetAsOutbound_transfersGetResponseAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetResponse> GetAsOutbound_transfersGetResponseAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToGetRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::StripeKiota.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetResponse>(requestInfo, global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;p&gt;Returns a list of OutboundTransfers sent from the specified FinancialAccount.&lt;/p&gt;
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::StripeKiota.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
        [Obsolete("This method is obsolete. Use GetAsOutbound_transfersGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersResponse?> GetAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersResponse> GetAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToGetRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::StripeKiota.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersResponse>(requestInfo, global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;p&gt;Creates an OutboundTransfer.&lt;/p&gt;
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.Models.Treasury.Outbound_transfer"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::StripeKiota.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::StripeKiota.Client.Models.Treasury.Outbound_transfer?> PostAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::StripeKiota.Client.Models.Treasury.Outbound_transfer> PostAsync(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::StripeKiota.Client.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::StripeKiota.Client.Models.Treasury.Outbound_transfer>(requestInfo, global::StripeKiota.Client.Models.Treasury.Outbound_transfer.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;p&gt;Returns a list of OutboundTransfers sent from the specified FinancialAccount.&lt;/p&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersGetRequestBody body, Action<RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// &lt;p&gt;Creates an OutboundTransfer.&lt;/p&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/v1/treasury/outbound_transfers", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder WithUrl(string rawUrl)
        {
            return new global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;p&gt;Returns a list of OutboundTransfers sent from the specified FinancialAccount.&lt;/p&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Outbound_transfersRequestBuilderGetQueryParameters 
        {
            /// <summary>A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ending_before")]
            public string? EndingBefore { get; set; }
#nullable restore
#else
            [QueryParameter("ending_before")]
            public string EndingBefore { get; set; }
#endif
            /// <summary>Specifies which fields in the response should be expanded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Returns objects associated with this FinancialAccount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("financial_account")]
            public string? FinancialAccount { get; set; }
#nullable restore
#else
            [QueryParameter("financial_account")]
            public string FinancialAccount { get; set; }
#endif
            /// <summary>A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("starting_after")]
            public string? StartingAfter { get; set; }
#nullable restore
#else
            [QueryParameter("starting_after")]
            public string StartingAfter { get; set; }
#endif
            /// <summary>Only return OutboundTransfers that have the given status: `processing`, `canceled`, `failed`, `posted`, or `returned`.</summary>
            [Obsolete("This property is deprecated, use StatusAsGetStatusQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("status")]
            public string? Status { get; set; }
#nullable restore
#else
            [QueryParameter("status")]
            public string Status { get; set; }
#endif
            /// <summary>Only return OutboundTransfers that have the given status: `processing`, `canceled`, `failed`, `posted`, or `returned`.</summary>
            [QueryParameter("status")]
            public global::StripeKiota.Client.V1.Treasury.Outbound_transfers.GetStatusQueryParameterType? StatusAsGetStatusQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Outbound_transfersRequestBuilderGetRequestConfiguration : RequestConfiguration<global::StripeKiota.Client.V1.Treasury.Outbound_transfers.Outbound_transfersRequestBuilder.Outbound_transfersRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Outbound_transfersRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
